### ISSUE TITLE
COX scouter blacklist still broken

### ISSUE THREAD

**Issue by w355osrs** [runelite-extended/runelite#1003]
Raids whitelist and blacklist color coding still not working. Only color codes that work at the moment is rope and the different crab rooms.

**Comment by Kyleeld** [comment]
are you building the client? if not, it will still be broken.

**Comment by w355osrs** [comment]
I don’t know what that means.

**Comment by Ganom** [comment]
> 
> 
> I don’t know what that means.

He means, if you're using the exe launcher, it will still be broken as the update hasn't been pushed to the exe launcher yet.

**Comment by w355osrs** [comment]
Oh thank you for clarifying! Thanks guys!
