### ISSUE TITLE
Menu Entry Swapper - Abyssal Zamorakian Mage "Teleport" overriden by "Trade"

### ISSUE THREAD

**Issue by GrimWrath** [runelite-extended/runelite#1008]
The "Trade" option overrides the "Teleport" option on the abyssal zamorakian mage when both "Trade" and "Teleport To Abyss" options are enabled under the "Talk-to" subsection of the menu entry swapper.

Workaround is to disable the trade option.

Settings to reproduce the bug:
![Settings to reproduce the bug](https://i.vgy.me/jx2DOU.png)

**Comment by Kyleeld** [comment]
the problem is, some would want trade as the first option, some would want teleport as the first option.

if you want to have teleport as the first option, disable trade, if you want trade as the first option, then enable trade.
