### ISSUE TITLE
Detached camera isn't able to moved around

### ISSUE THREAD

**Issue by JourneyOver** [runelite-extended/runelite#1009]
**Describe the bug**

Detached camera doesn't seem to be able to be moved anywhere only able to be pitched up/down/left/right, unless the "Remap camera" config option in "key remapping plugin" is disabled.

**To Reproduce**
1. Make sure "Remap camera" config option in "key remapping plugin" is enabled.
1.5 Enable detached camera in dev tools
2. Press wasd to try and move the camera to a different location on screen and notice it's not able to be moved
3. go into Key remapping plugin and disable the remap camera option
4. try to move the camera again and notice that it's able to be moved around now.

**Expected behavior**

For detached camera to be able to be moved to another location without having to disable the remap camera config in the key remapping plugin.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 x64 bit
 - RuneLite version: 1.5.29-snapshot
 - Launcher version: 1.6.3-snapshot

**Additional context**

Nothing really noticeable in the logs (but if you want them let me know and I'll get them up) and this one I don't really know how to fix myself sadly or I'd just of sent in a PR.

**Comment by Kyleeld** [comment]
can you confirm if the same happens in normal RL?

**Comment by JourneyOver** [comment]
Hmm looks to be an issue in normal RL now as well from the looks of it, I know it used to work just fine a long time ago while having the key remapping plugin remap camera stuff turned on.

**Comment by Kyleeld** [comment]
if this is occurring in normal RL, this will likely get resolved upstream, i would suggest raising it to them.
