### ISSUE TITLE
Bank Tags: Remove separators in tag tabs is bugging out.

### ISSUE THREAD

**Issue by JourneyOver** [runelite-extended/runelite#1016]
**Describe the bug**

Bank Tags: Remove separators in tag tabs config option seems to only work sometimes. half the time of opening the bank or switching away from the tag tab and then back will cause the separators to come back again.

**To Reproduce**
(it's better to watch the gif down below to better understand this)
1. Make sure "Remove separators in tag tabs" config option in "Bank Tags" is enabled.
2. Open a bank
3. switch between tag tabs and bank tabs and see what happens
4. ...

**Expected behavior**

For bank tab separators to never show unless the remove separators in tag tabs config option is disabled.

**Screenshots**

I took a gif instead of a screenshot to better help understand the issue.
![07-16-2019_18-35-45](https://user-images.githubusercontent.com/13910285/61337187-e60fc800-a7f9-11e9-9a93-bf1b2a6503ab.gif)

**Environment (please complete the following information):**
 - OS: Windows 10 x64 bit
 - RuneLite version: 1.5.29-snapshot
 - Launcher version: 1.6.3-snapshot

**Additional context**

It'll sometimes happen upon opening the bank for the first time as well, which then upon closing bank and re-opening will temporarily remove the separators until you do anything in the gif above. 

As usual nothing in logs to really help out with this issue, and as this (remove separators in tag tabs) is not a feature in normal runelite I'm unable to test anything upstream.

**Comment by Kyleeld** [comment]
does this happen in normal RL too? from memory i saw something yesterday saying it did

**Comment by JourneyOver** [comment]
@Kyleeld 	read my last bit in the additional context xD specifically this bit:

> as this (remove separators in tag tabs) is not a feature in normal runelite I'm unable to test anything upstream.

**Comment by JourneyOver** [comment]
answered a bit more in discord about this. I never experienced the bug you was talking about in normal RL so I can't say for sure if that is possibly the cause or not. Think we need more test cases to see what is going on possibly.
