### ISSUE TITLE
fight caves had fight

### ISSUE THREAD

**Issue by reigndespair** [runelite-extended/runelite#1018]
Been a while since I attempted the fight caves, but after the last update that I attempted the fight caves. If you stept outside of the range of had it would not show what was attacking next. Even when back in range. For lower levels this is a must, because position is every thing when it comes to healers. Also maybe a small box around the healers would also help for quickly targeting then going back to jad.

**Comment by Ganom** [comment]
Not possible for request 1, it would require a significant amount of work and the plugin would have to be completely rewritten.

**Comment by reigndespair** [comment]
That's a shame, because that's the more important one in my opinion. It never used to do it when the prayer guides was on the side, but when it changed to over the head of jad then that issue came. Maybe have the prayer guides on both next to the inv, and over jad?
