### ISSUE TITLE
Lags when using pvp plugins in wilderness

### ISSUE THREAD

**Issue by Thisissue** [runelite-extended/runelite#1019]
Anyone know of a fix for the lag in runelite+? 
The small stutter / glitches are still not fixed for me. I tried using hardware acceleration off (--mode=OFF), using the jar or executable, and turning off the world hopper. All to no avail. I did notice it seems to happen more often during pking than normal playing. I think it might be because of world hopping a lot. Here's a video showing the glitches, they occur every 5 seconds or so. https://streamable.com/6pxyu
I'm on a i5-6400@2.70 ghz, 1070 ti, 16 gb ram ddr4, ssd. Computer specs should not be a problem. 
Plenty of mates of mine have it too. Once the lagging starts occuring, it will not go away until you restart the whole client.

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue with the latest update :)

**Comment by Thisissue** [comment]
Ill keep u up to date! give me 3hours of pking, see if it still giving any issues

**Comment by Thisissue** [comment]
YE seems fixed, haven't got any problems! Thanks!!
