### ISSUE TITLE
Quest List: Filter/Search doesn't show up unless you disable/re-enable the plugin

### ISSUE THREAD

**Issue by JourneyOver** [runelite-extended/runelite#1027]
**Describe the bug**

quest list plugin seems to be bugged (doesn't show the filter/search stuff), it only works temporarily if you disable and then re-enable the plugin while on the quest list, but if you switch tabs away from the quest list to one of the others like achievement diary or minigame or kourend favour the filter/search disappear again

**To Reproduce**
1. Login to game with the quest list plugin enabled
2. go to quest list tab and notice the search/filter is missing
3. disable and then re-enable the quest list plugin and notice the search/filter come back
4. switch away from quest list to achievement diary or one of the other 2 and then back the quest list
5. notice the search/filter is missing again until you follow step 3 again.

**Expected behavior**

For the search/filter from the quest list plugin to always be there if the plugin is enabled.

**Screenshots**

![07-18-2019_17-10-58](https://user-images.githubusercontent.com/13910285/61495620-16cd3a00-a97f-11e9-8c21-003f6b88245f.gif)

**Environment (please complete the following information):**
 - OS: Windows 10 x64 bit
 - RuneLite version: 1.5.29-snapshot
 - Launcher version: 1.6.3-snapshot

**Additional context**

This problem does not exist on normal runelite (have built and tested on the latest normal runelite as well), seems to only be an issue on runelite+

#1016 	still seems to be an issue as well.

**Comment by Ganom** [comment]
This is likely due to the client script changing in the gamepack update, when we do an upstream merge this will likely be fixed.

**Comment by JourneyOver** [comment]
Great, hopefully it does fix it when doing an upstream merge as I like having the search and filter for the quest list.

**Comment by JourneyOver** [comment]
This looks to be fixed now in master.
