### ISSUE TITLE
grand exchange: Actively traded price showing twice

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#1039]
**Describe the bug**
When buying an item in the GE, the OSBuddy traded price is showing twice

**To Reproduce**
Try to sell an item on the GE

**Expected behavior**
One line of the price, not two

**Screenshots**
https://i.imgur.com/JtkI08O.png 

latest pull to intellij: 229f2c9
this issue is also in the live client

**Comment by f0rmatme** [comment]
rxjava causing this bug?

**Comment by JourneyOver** [comment]
Could be possibly, he isn't the only one having this issue, I have it as well.
