### ISSUE TITLE
grandexchangeplugin: Afford string showing on Sell interface

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#1045]
Currently (dev build) it shows the Afford string if you click the Sell button on the GE then click the item in your inventory

Clicking the item that you want to sell on the default interface (showing all 6 offers) wont show the text

I hope this gifv explains it too: https://i.imgur.com/U4Q5hiE.gifv

**Comment by Owain94** [comment]
@ganom Could you take a look at this when you have time?

**Comment by SRLJustin** [comment]
this isn't fixed:

https://i.imgur.com/BHeG30V.png

using latest build

**Comment by zeruth** [comment]
This is fixed now, so will remain closed
