### ISSUE TITLE
Loot Tracker not tracking loot

### ISSUE THREAD

**Issue by Connerbtw** [runelite-extended/runelite#1052]
Pretty simple and simular to title; when killing monsters, the loot is not tracked. It's been fine all week and I've had no issues, but this morning I woke up to my client frozen (fell asleep with it on) and reopened the client. After killing around 100 lizardman shamans, I realized that none of the loot was showing up on my tracker. Since I killed some earlier in the week, I assumed it just wasn't showing up on my Daily loot tracker and checked monthly; yet, nothing there. I reset all tracked loot and still didn't track any kills. Tried killing addy dragons, and loot still wasn't tracked.

This could be client side, but I doubt it since I restarted both my computer and my client. After checking the Discord, I saw that there have been some issues with the recent update and figure this is one of the small flaws.

**Comment by Kyleeld** [comment]
fixed next update.
