### ISSUE TITLE
grandexchange: Can afford doesn't update anymore with price per item

### ISSUE THREAD

**Issue by JourneyOver** [runelite-extended/runelite#1061]
**Describe the bug**

`Can afford` doesn't update anymore when changing the `price per item` in the grand exchange.

**To Reproduce**
1. Have `afford quantity` enabled in Grand exchange plugin.
2. Open a buy offer in the grand exchange for a random item
3. change `price per item` up or down.
4. ...

**Expected behavior**

For the `can afford` to update to show how many I can afford whenever I change the `price per item`

**Screenshots**

![java_07-19-2019_23-51-13](https://user-images.githubusercontent.com/13910285/61574485-03f15d00-aa86-11e9-9738-95d60f2d5704.png)
![java_07-19-2019_23-51-28](https://user-images.githubusercontent.com/13910285/61574486-0489f380-aa86-11e9-8d88-4036f649cc65.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64 bit
 - RuneLite version: 1.5.30-snapshot
 - Launcher version: 1.6.3-snapshot

**Additional context**

Ganom told me to make an issue for this so he can remember to fix it.

This was the issue `it can never update once set`

we all blame Kyle obviously for this ;P

**Comment by JourneyOver** [comment]
@Ganom Kyle didn't believe me when I told him that the current layout would cause issues with items with long descriptions when he changed the layout of the grand exchange to be how it is now but 
![java_07-20-2019_01-38-29](https://user-images.githubusercontent.com/13910285/61575278-63a03600-aa8f-11e9-966b-b89f2864f6c5.png)

as you can see the little cut off on text at the bottom for the `OSBuddy Actively traded price` so maybe while fixing the above issue you can also look into fixing this as well? (as you know blame Kyle again) :p

**Comment by pklite** [comment]
fixed in #1583
