### ISSUE TITLE
freezetimers: TB Timer

### ISSUE THREAD

**Issue by Kyleeld** [runelite-extended/runelite#1065]
TB Timer should be removed if one of the following conditions are met:

- [x] 1) the player who is tele blocked dies.
- [x] 2) the player who is tele blocked leaves the wildy.
- [x] 3) the player who is tele blocked enters a safe zone.
- [x] 4) if the player who cast tele block is killed by you and you get the following message: "Your Tele Block has been removed because you killed 1G Molly.'"

**Comment by Lohouse** [comment]
1 and 4 are fixed in https://github.com/runelite-extended/runelite/pull/1064 . 2 and 3 remain to be done.

**Comment by pklite** [comment]
we should make sure that number 2 isn't applied in pvp worlds because i don't think it gets removed exiting wildy in pvp worlds. also iirc the immunity after a TB wears off is 45 seconds

**Comment by Lohouse** [comment]
Correct.

We should also check the following:
Does a player keep the teleblock immunity timer after leaving the wilderness/entering a safezone and after killing their teleblocker (both in teleblock phase and immunity phase)

**Comment by Lohouse** [comment]
Everything listed above is fixed in https://github.com/runelite-extended/runelite/pull/1064 .
This issue can be closed when it's merged into master.
