### ISSUE TITLE
Slayer count going down by 5's each kill instead of 1

### ISSUE THREAD

**Issue by Sithari98** [runelite-extended/runelite#1077]
only an issue on runelite plus. regular runelite slayer count working as expected. tried resetting settings to default and getting new tasks, counter will still start at correct number and go down by 5 each kill.

**Comment by Ganom** [comment]
More information please, what monster? every monster? Using bracelets? default world?

**Comment by Sithari98** [comment]
its done this every monster so far, i am on the deadman mode world getting 5x xp. could that be causing this?

**Comment by Ganom** [comment]
> 
> 
> its done this every monster so far, i am on the deadman mode world getting 5x xp. could that be causing this?

Yes,

**Comment by Sithari98** [comment]
how could runelite understands the 5x on this world but runelite plus doesnt?

**Comment by Ganom** [comment]
> 
> 
> how could runelite understands the 5x on this world but runelite plus doesnt?

@sdburns1998 made significant changes to the plugin to make it much better than the RL one, seems that was one thing he missed unfortunately.

**Comment by Sithari98** [comment]
can anything be done about this?

**Comment by SRLJustin** [comment]
I guess we could add a world type check to the countdown section to handle DMM worlds better

**Comment by Owain94** [comment]
@Sithari98 Isn't deadman 10x the XP?

**Comment by Kyleeld** [comment]
normal deadmin is, w45 is 5x
