### ISSUE TITLE
!Gc command doesn't work in RL+

### ISSUE THREAD

**Issue by ZainTheOne** [runelite-extended/runelite#1080]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
!gc command is not working

**To Reproduce**
1. If you type "!gc" it doesn't work

**Expected behavior**
The command works in RL but not in RL+. It is supposed to tell you the count of gambles from the minigame "barbarian assault"

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [1.5.30]
 - Launcher version: [1.6.3]

**Comment by Kyleeld** [comment]
2019-07-23 00:43:46 [pool-2-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup error
