### ISSUE TITLE
Hardware acceleration working in RL, but not in RL+ (Graphical glitches)

### ISSUE THREAD

**Issue by samuk190** [runelite-extended/runelite#1085]
Ryzen 7 1700, gtx 1070 and windows 10.

I know that if i put mode=off in startup command I can disable hw aceleration and it will "fix"
but hw aceleration is very important and I think it causes some bugs if its disabled I dont know.

**Comment by Kyleeld** [comment]
https://github.com/runelite-extended/runelite/wiki/Disable-Hardware-Acceleration
