### ISSUE TITLE
Developer Tools incorrect ID

### ISSUE THREAD

**Issue by UWPA** [runelite-extended/runelite#1089]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Developer Tools'
2. Click on Purple Graceful Cape
3. Skip cause 3 is gay

**Expected behavior**
Purple Cape with ID 13582 shows as ID 13581

**Screenshots**
I got video
https://youtu.be/befqXt1tpu8

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - RuneLite version: [e.g 1.5.30]
 - Launcher version: [e.g 1.6.3 - Snapshot]

**Additional context**
None

**Comment by Ganom** [comment]
Not incorrect, but for tmorph it is incorrect.
