### ISSUE TITLE
runeliteplus: Discord Presence always showing custom presence

### ISSUE THREAD

**Issue by GantaRS** [runelite-extended/runelite#1115]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Discord always detecting RuneLite+ custom presence

**To Reproduce**
1. Go to RuneLitePlus plugin.
2. Enable RL+ Presence
3. View Discord presence

**Expected behavior**
The Discord presence is supposed to show "playing RuneLite"

**Screenshots**
https://i.imgur.com/vQtAGK5.png (custom presence disabled)
https://i.imgur.com/rTMGGky.png (custom presence enabled)
**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: v1.5.30+
 - Launcher version: v1.5.30+

**Additional context**

**Comment by SRLJustin** [comment]
Once you turn off Custom presence, have you added 'RuneLite' as a game on your discord?

**Comment by GantaRS** [comment]
> Once you turn off Custom presence, have you added 'RuneLite' as a game on your discord?

Yes, and it still shows as RuneLite+
It worked before, but stopped after this update

**Comment by Ganom** [comment]
We are making everyone use rl+ presence now.



Nah, it was an accident when we swapped to gradle, thanks for reporting.

**Comment by SRLJustin** [comment]
rl+ presence is now forced: #1136 - this can be closed
