### ISSUE TITLE
worldmap: House portal teleport tooltips

### ISSUE THREAD

**Issue by permedd** [runelite-extended/runelite#1117]
**Additional context**

When you open the world map and hoover over the house portal it should say which house is that portal called.

![](https://user-images.githubusercontent.com/37475765/44958470-9e7d9780-aed8-11e8-9aa5-37255a3a9163.png)

For example when I hoover my mouse over the house portal it should say Traverley house which is on the screenshot etc

**Comment by Kyleeld** [comment]
does this occur in normal RL also?

**Comment by supermxn** [comment]
Yes it does

**Comment by SRLJustin** [comment]
Normal RuneLite: https://i.imgur.com/J52HVda.png

**Comment by permedd** [comment]
I forgot to edit the “house portal” to “traverley house”.

**Comment by Kyleeld** [comment]
as per above, this happens in normal RL, therefore a fix will likely come from upstream
