### ISSUE TITLE
Gradle: Daemon not releasing file locks.

### ISSUE THREAD

**Issue by zeruth** [runelite-extended/runelite#1119]
This is an intermittent bug that makes it impossible to rebuild after a failed build

It is rather easy to work around by opening Task Manager and killing java processes that aren't idea (the Gradle daemon), then running the clean build tasks again.

**Comment by Owain94** [comment]
Can you try to reproduce with https://github.com/runelite-extended/runelite/pull/1111/commits/220e150ca1893aa61cae4ffd866e40b7f1a19907

**Comment by zeruth** [comment]
Yes it is still reproducable, even after killing the daemon
