### ISSUE TITLE
Add plugins from other clients

### ISSUE THREAD

**Issue by permedd** [runelite-extended/runelite#1124]
I like how you guys bring some of other clients plugins etc to runelite plus but wouldn't it be good to add all their plugins?
the clients that have good plugins and should be added to this client is
- lyzrdlite (PvM based)
-Exilent (PvP based)
every week they do an update, maybe when you're bringing runelites plugin to this client you can just get 'all of their plugins' as well?

its little annoying how we have to switch from one client to other just for some plugins that other clients don't have etc, will be good to have all the clients plugin to one client.

i also know that you guys have some plugins from other clients such as lyzrdlite for CoX or DoB but can you get all their plugins added to your client same goes for Exilent client.

i am sure if you add their plugins to your client, i am sure so many players will be using this client and also they wouldn't be switching from 1 client to another.

**Comment by supermxn** [comment]
suggest any plugins you need and we may or may not add it.

**Comment by Kyleeld** [comment]
please suggest individual plugins rather than this.
