### ISSUE TITLE
timer for items on the floor  which are going to disapear

### ISSUE THREAD

**Issue by permedd** [runelite-extended/runelite#1125]
**Additional context**

this suggestion is already added but it's only added to when you hold 'ALT' on your keyboard can there be an option to see the timer without holding ALT, and holding ALT.

![image](https://user-images.githubusercontent.com/37475765/61869885-a0778d00-aed4-11e9-8174-96b98fc9b71a.png)
as you can see the timer is not there where it shows when the item will disappear, this is where i am not holding ALT

![image](https://user-images.githubusercontent.com/37475765/61870007-e59bbf00-aed4-11e9-83d3-b4b72ddfecf3.png)
and here it shows the timer, this is where i am holding ALT on the keyboard.

**Comment by JourneyOver** [comment]
Was solved in discord.
