### ISSUE TITLE
Rune pouch font

### ISSUE THREAD

**Issue by SerParker** [runelite-extended/runelite#1127]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Rune pouch font is bold and cannot be changed

**Screenshots**
https://i.imgur.com/lDAZ9Xj.jpg
https://i.imgur.com/eFyP9Jc.jpg

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.30
 - Launcher version: RuneLitePlus 2.1.0.0 

**Additional context**

**Comment by Kyleeld** [comment]
Duplicate, known issue
