### ISSUE TITLE
hoovering on top of the xp orb.

### ISSUE THREAD

**Issue by permedd** [runelite-extended/runelite#1154]
**Additional context**
- on the xp orb we should be able to see what we want to see what i mean is right now whenever we move out mouse on top of the xp orb we see this which is located on the left side of the image underneath.

![image](https://user-images.githubusercontent.com/37475765/61998006-66a7b180-b0a1-11e9-8e01-102af0745628.png)

but I want to pick what i want to see out of all the options which are;
 - name of skill, current XP, Kills Left, XP Left, XP per hour, Timeleft.
we should be able to pick which ones we want to see out of the list above.

so, for example, you can make a plugin at the 'configuration' which is called 'XP Orb' 
and in that XP Orb you can have it saying
do you want to see **name of skill,** 
do you want to see **current XP,** 
do you want to see **Kills Left,** 
do you want to see **XP Left,** 
do you want to see **XP per hour,** 
do you want to see **Timeleft.**

or you don't have to have it saying 'do you want to see' you can just have the enable/disable plugin which is this 
![image](https://user-images.githubusercontent.com/37475765/61998059-2c8adf80-b0a2-11e9-8fc1-8a670336185b.png)

**Comment by permedd** [comment]
if you didn't understand let me know, i will sure to explain it properly.

**Comment by Kyleeld** [comment]
Would likely come from upstream, this isn’t something we would implement
