### ISSUE TITLE
quest list

### ISSUE THREAD

**Issue by permedd** [runelite-extended/runelite#1167]
**Describe the bug**
- on the configuration, the 'quest list' is always active for me but while the configuration is active the quest list on the quest tab disappears

**To Reproduce**
1. quest tab

**Expected behavior**
- when the configuration is active, the quest list button should always be there should not disappear.

**Screenshots**

![image](https://user-images.githubusercontent.com/37475765/62008169-3cf89400-b14e-11e9-9597-14a6a3a8f915.png)
- this is how the quest list button when the quest list configuration is on.

![image](https://user-images.githubusercontent.com/37475765/62008226-53065480-b14e-11e9-89ce-560237b2d84e.png)
- this is another screenshot of the quest list it disappears when the quest list configuration is on.

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - latest version

**Comment by Kyleeld** [comment]
Fixed in latest pull
