### ISSUE TITLE
Ground markers Plugin:  Broken in dev builds

### ISSUE THREAD

**Issue by JourneyOver** [runelite-extended/runelite#1170]
**Describe the bug**

Shift+right click and placing a ground marker does not seem to do anything in latest dev builds. No ground markers appear, and the shift+right click options remain as "mark" for all ground marker options (the separate color options) even if clicking different ones.

**To Reproduce**
1. Build from master branch
2. Open game and login (have ground markers plugin enabled)
3. Try to place a ground marker
4. ...

**Expected behavior**

For ground markers to show up when shift+right clicking and placing a ground marker down in the latest dev builds

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 x64 bit
 - RuneLite version: 1.5.30-snapshot
 - Launcher version: 2.1.0.0

**Additional context**

Ground markers appear to be working correctly in the normal RL+ launcher/client, it appears to only be broken when building from source. Not sure how long they have been broken for as I haven't had to use them in a while.

Testing normal runelite dev builds they appear to be working as well (though they don't have the separate color options like RL+ does anymore).

**Comment by Ganom** [comment]
Any errors, anything?

**Comment by JourneyOver** [comment]
Nope no errors or really anything in the logs at all. @Ganom

[client.log](https://github.com/runelite-extended/runelite/files/3439584/client.log)
This is my latest log. (Even discord RL+ presence seems to be broken in dev builds as well as I haven't seen it in a while now and it hasn't appeared in my logs either in a while)

**Comment by JourneyOver** [comment]
Fixed in latest commit
