### ISSUE TITLE
Client occasionally crashes even with latest Java installed

### ISSUE THREAD

**Issue by ZainTheOne** [runelite-extended/runelite#1188]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Client randomly crashes without any error. Happens around 2/3 times a day and not affiliated with a certain activity in-game.

**To Reproduce**
It feels like clicking too much in a short amount of time causes this, like client feels too heavy and just crashes

**Expected behavior**
Client running nicely

**Screenshots**
null
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - RuneLite version: [1.5.30 -SNAPSHOT]
 - Launcher version: [2.1.1.0]

**Additional context**
Following are the logs from a week. If it matters i first used to run rl+ from .jar file now i do from the .exe file. 

[launcher_2019-07-22.0.log](https://github.com/runelite-extended/runelite/files/3443521/launcher_2019-07-22.0.log)
[launcher_2019-07-23.0.log](https://github.com/runelite-extended/runelite/files/3443522/launcher_2019-07-23.0.log)
[launcher_2019-07-24.0.log](https://github.com/runelite-extended/runelite/files/3443523/launcher_2019-07-24.0.log)
[launcher_2019-07-25.0.log](https://github.com/runelite-extended/runelite/files/3443524/launcher_2019-07-25.0.log)
[launcher_2019-07-26.0.log](https://github.com/runelite-extended/runelite/files/3443525/launcher_2019-07-26.0.log)
[launcher_2019-07-27.0.log](https://github.com/runelite-extended/runelite/files/3443526/launcher_2019-07-27.0.log)
[launcher_2019-07-28.0.log](https://github.com/runelite-extended/runelite/files/3443527/launcher_2019-07-28.0.log)

**Comment by Kyleeld** [comment]
please provide client logs.

**Comment by ZainTheOne** [comment]
> please provide client logs.

"launcher_2019-07-22.0.log"

Are these not logs or are launcher logs and client logs different. If they are please tell the directory

**Comment by Kyleeld** [comment]
same directory.

it will be for instance: Client_2019-07-22.0.log

**Comment by ZainTheOne** [comment]
Havent crashed since full clean reinstall,please close my ticket. Thanks
