### ISSUE TITLE
Gradle Build doesn't work when building with JDK 11 or 12

### ISSUE THREAD

**Issue by Bartvhelvert** [runelite-extended/runelite#1199]
**Describe the bug**
When selecting JDK 11 or 12 as JVM in gradle the project won't build and produce the following error: Cause: repository not found: GRADLE_USER_HOME\.gradle\daemon\5.5.1\.git

**To Reproduce**
1. Go to gradle settings in Intelij IDEA
2. Set Gradle JVM to either JDK 11 or 12 

**Expected behavior**
Builds the project.

**Environment (please complete the following information):**
 - OS: Windows 10 
 - RuneLite version:  Master 785479c648ef5439c944e8003b36ebb2d038a2a0

**Additional context**
Using JDK 8 works. Using JDK 9 or 10 might also not work.

**Comment by Kyleeld** [comment]
You have to use , same as maven
