### ISSUE TITLE
NPE with Gauntlet Plugin

### ISSUE THREAD

**Issue by bigmemes420** [runelite-extended/runelite#1227]
**Describe the bug**
Opening the options for the gauntlet plugin causes an NPE

**To Reproduce**
1. Go to the Gauntlet plugin
2. Click on the cog icon to go into settings

Here's the logs https://pastebin.com/raw/wyRyrahq

**Comment by ReeeMan** [comment]
Did you build a previous version yourself?

There is something wrong in your -. Runeliteplus\settings file. (can't remeber exact name I'm on mobile) but find the line gauntlet.highlightResourcesColor

And delete that line because most likely it's set to something like false instead of a colour.

**Comment by bigmemes420** [comment]
That was the issue, thanks
