### ISSUE TITLE
Overlay font broken/inconsistent

### ISSUE THREAD

**Issue by laska89** [runelite-extended/runelite#1238]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Unable to change overlay font. Rune pouch is always non-bold, while other items such as slayer helm are always bold. 

**To Reproduce**
1. Try to change font style under runelite settings
2. See that it has no effect on item overlays

**Expected behavior**
Font style should correspond to what is set in settings.

**Screenshots**
https://i.imgur.com/YeDcexp.png

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.31
 - Launcher version: 2.1.2.0

**Additional context**
Before the update on 8/1/2019 the rune pouch font was always bold and it was impossible to change. Now it is the opposite. Also, going back to the vanilla runelite client, it does not have this issue.

**Comment by Owain94** [comment]
This issue has been resolved in #1249
