### ISSUE TITLE
Theatre of Blood Soteseg Solo Maze not working.

### ISSUE THREAD

**Issue by JasonDMG** [runelite-extended/runelite#1280]
**Description of the bug**
In the current Theatre of Blood plugin there is a plugin called "Mark Soteseg maze solo". Unfortunately this feature no longer works when doing solo tob.

**To Reproduce**
1. Kill Maiden, Bloat, Nylocas and get to Soteseg.
2. Start Soteseg as your normally do.
3. Wait for the Maze.
4. Now when you ran across the maze in the underworld you won't see the pattern in the overworld.
5. Die. Or have screenshotted it to do it the old fashion way.

**Expected behavior**
It should have shown the Maze layout in the overworld and underworld. It didn't show in any.

**Comment by Ganom** [comment]
Have you verified this actually worked before hand? We haven't changed anything regarding the maze.

**Comment by JasonDMG** [comment]
It worked before the whole bytecode patcher etc. Aka like 3+ months ago

**Comment by JasonDMG** [comment]
I'm currently trying again and see what is happening in the client logs. Will keep you updated. If nothing happens according the logs we could make it a feature.

**Comment by Ganom** [comment]
Verified working.
