### ISSUE TITLE
Master clue loot tracker merged with medium clues

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite-extended/runelite#1292]
I noticed this last week but didn't post as I thought it would have been fixed this week but it hasn't

![](https://i.imgur.com/OPRsFB9.png)

**Comment by pklite** [comment]
has this always been happening or did it just start last week?

**Comment by AverageHumanoid** [comment]
started just last week

**Comment by AverageHumanoid** [comment]
Seems to be fixed now after this week's update.
