### ISSUE TITLE
Feature Request: Idle Plugin Expansion

### ISSUE THREAD

**Issue by Coollegolas** [runelite-extended/runelite#1318]
Would it be possible to add an idle alert for just being idle? I'm picturing it for an alt where I've moved between objects and am now just standing, so the main flash won't ever happen since I moved to a point to stand still. For instance, you're crafting blood runes and get stopped halfway to the altar, but you don't notice and forget about the alt.

It would hopefully be configurable and generally set to a long enough time that it wouldn't be going off all the time (I'd probably set it to 15-20 seconds default?) and should definitely be able to be isolated from the rest of the idle alerts so that it's not overriding or happening when people don't want it to.

Hopefully that's fairly clear. Let me know if there's any questions,

**Comment by Kyleeld** [comment]
Already exists
