### ISSUE TITLE
The runelite world hopper isn't showing pings in runelite+

### ISSUE THREAD

**Issue by ZainTheOne** [runelite-extended/runelite#1319]
**Describe the bug**
The runelite world hopper isn't showing pings in runelite+

**To Reproduce**
Open world hopper from the pannel

**Expected behavior**
See pings from world hopper like it still works in runelite

**Screenshots**
![image](https://user-images.githubusercontent.com/41491341/62978493-d5736180-be3a-11e9-9220-c1e7a51db0f8.png)

**Environment (please complete the following information):**
 - OS: Windows 10 
![image](https://user-images.githubusercontent.com/41491341/62978598-18353980-be3b-11e9-9806-1d57fff7252b.png)

**Comment by Crystalknoct** [comment]
If I am not mistaken its fixed just needs to be pushed to live client.

**Comment by Kyleeld** [comment]
Known issue, fixed next update
