### ISSUE TITLE
I miss seeing my ping in the top right corner, why was this removed

### ISSUE THREAD

**Issue by ZainTheOne** [runelite-extended/runelite#1320]
**Is your feature request related to a problem? Please describe.**
Seeing your ping in the top corner helps if the internet is bad or is runelite lagging

**Describe the solution you'd like**
Have the old feature back
![image](https://user-images.githubusercontent.com/41491341/62978994-0e600600-be3c-11e9-9647-6fd2f76e1379.png)

This was broken for a week and removed in the next one, i really miss it. Please consider adding it back

**Comment by Crystalknoct** [comment]
It's a known bug build the client yourself to fix it. https://i.imgur.com/Wdu6qjs.png
Your last issue was closed and answered.

**Comment by sunha7** [comment]
Turn on `Display current ping` in the World Hopper plugin, might still get blank ping till its fixed in live client though

**Comment by ZainTheOne** [comment]
> Turn on `Display current ping` in the `World Hopper` plugin, might still get blank ping till its fixed in live client though
> 
> Edit: this got moved from the `Performance` plugin to the `World Hopper` plugin

Thank You!!
