### ISSUE TITLE
Skill Specs Custom Cursor

### ISSUE THREAD

**Issue by TzHaar-Bomba** [runelite-extended/runelite#1322]
Please add a skill specs cursor https://imgur.com/a/d52c9ln that is the best image for the cursor

**Comment by Ganom** [comment]
M8 you don't even deserve the kill bro it is what it is at the end of the day this game takes HUGE FAT STEAMY DUMPS on my fkn head bro and I hate it! I FKN HATE IT BRO! Where is specs' RNG man I'm sAT THERE 👏  AB  👏  SO 👏 LUTE 👏  LY FI 👏 NES 👏 SING THE CUNT and I don't get shit for it ever, fuck off, whatever. Guy sits there and he 115s in brid and he specs me his ags into gmaul, THROUGH THE PRAYER might I add. Doesn't matter. Doesn't fkn matter. Prayer means fk all on this game. Sad. Sad. Sad scam game.
