### ISSUE TITLE
Font settings not saving

### ISSUE THREAD

**Issue by xHous** [runelite-extended/runelite#1339]
Font settings in the Runelite plugin aren't saving upon exit. 
https://i.imgur.com/wcT3wnC.png
These are my saved settings which stay the same in the options but don't in the client, which are meant to look something like this ingame:
https://i.imgur.com/YYJSYmc.png
But whenever I relaunch they default to this:
https://i.imgur.com/AR5OTwj.png

**Comment by xanderqixter** [comment]
yeah. vaguely annoying. happening to me as well

**Comment by ryanleonard1** [comment]
Also experiencing this issue...

**Comment by pklite** [comment]
#1540 fixes this because font settings used an enum too

**Comment by 40Cakes** [comment]
I'm still experiencing this issue after #1540, any ideas?
