### ISSUE TITLE
Menu entry custom swapper not working on Torfinn

### ISSUE THREAD

**Issue by GalaxyKindred** [runelite-extended/runelite#1377]
**Describe the bug**
used custom swap on  torfinn so its set to collect instead of travel, it is not swapping.

**Expected behavior**
expecting ti to swap travel with collect so left click is collect

**Screenshots**
https://imgur.com/pHHBuDs

**Environment (please complete the following information):**
 - OS: win 10
 - RuneLite version: 1.5.32-snapshot
 - Launcher version: 2.1.3.1

**Comment by xKylee** [comment]
added to 1376
