### ISSUE TITLE
Ardougne Cape 4

### ISSUE THREAD

**Issue by hmmyeaaas** [runelite-extended/runelite#1385]
Ardy cape 4 left click now takes to monastery even when the option is ticked off in plugins - possible some overlap from left click teleports.
Additionally, shift click rebinds don't work on this item.

**Comment by xKylee** [comment]
is this still an issue?

**Comment by xKylee** [comment]
cannot re-produce. likely a custom swap interfering.

i would suggest taking a look at your custom swaps.
