### ISSUE TITLE
AOE Warning Indicator for Ice Demons Shows When Ice Bursting

### ISSUE THREAD

**Issue by calebcrowe** [runelite-extended/runelite#1404]
**Describe the bug**
After doing a raid with the Ice Demon AOE Warning plugin enabled, when you leave the raid the same overlay appears when casting Ice Burst

**To Reproduce**
1. Do a raid at chambers of xeric
2. Finish the raid
3. Cast Ice Burst
4. See Indicator. When Ice Demon AOE warning is disabled, there is no indicator when casting ice burst.

**Expected behavior**
There should be no indicator.

**Comment by f0rmatme** [comment]
#1436
