### ISSUE TITLE
Some textures dont load correctly with the GPU option enabled

### ISSUE THREAD

**Issue by laurenceschellevisch** [runelite-extended/runelite#1416]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
This happens when the GPU is activated atleast on my runelite plus. It makes the capes look like 

**To Reproduce**
1. Go to runelite settings and type GPU
2.Turn it on

**Expected behavior**
Normal render or textures

**Screenshots**
this https://gyazo.com/d21ac9a44b18bac9476edd0a56bcdd13 GPU on

https://gyazo.com/b5ebc77775111d71b324a605ba50705c GPU off
https://gyazo.com/75c065d80496266b9f6927d11b120d9c GPU on

**Environment (please complete the following information):**
 - OS: [Windows]
 - RuneLite version: [1.5.32-SNAPSHOT]
 - RuneLite PLUS version: [2.1.3.1]

**Additional context**
This also occures in resisable.

**Comment by Ganom** [comment]
upstream issue.

**Comment by xKylee** [comment]
fixed upstream to. will be in next update.

**Comment by laurenceschellevisch** [comment]
what is the reloase date on that?

**Comment by f0rmatme** [comment]
there isn't one, runelite updates whenever
