### ISSUE TITLE
Blackjacking not working

### ISSUE THREAD

**Issue by helpmeplsineedhelp** [runelite-extended/runelite#1459]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

The menu entry swapper for black jacking is not working. it is stuck on pick pocket.

**To Reproduce**
1. Go try to blackjack
2. See that it is broken.

**Comment by xKylee** [comment]
fixed in 1460
