### ISSUE TITLE
Time Tracking not working

### ISSUE THREAD

**Issue by Nickicipi** [runelite-extended/runelite#1472]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Time Tracking feature not working, not tracking patches or birdhouses, will stay at 'Done' even when a new plant is planted. Some buttons unclickable

**To Reproduce**
Start the client and attempt to use Time Tracking

**Expected behavior**
Time to be tracked properly from start to finish as well as buttons working.

**Screenshots**
![image](https://user-images.githubusercontent.com/54641310/63881669-618a9a80-c99e-11e9-8abd-1ac84a3288ad.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - RuneLite version: [RuneLitePlus 2.1.4.0]
 - Launcher version: [Latest]

**Comment by xKylee** [comment]
Already fixed

**Comment by xKylee** [comment]
It’s already fixed, wait for the next update
