### ISSUE TITLE
Farming Timers (Time Tracking) not Displaying for Farming Skill

### ISSUE THREAD

**Issue by unmetnik** [runelite-extended/runelite#1475]
When clicking the 'clock' icon known as "Farming Timers" to display an overview of how Tree Patches, Herb Patches and Fruit Tree Patches **are not displaying when left-clicked in the Time Tracking section for the Farming skill**.

There is no response when the tree, fruit free or herb (or any other) icon is clicked.

Have un-installed and re-installed through website and problem still occurs.   Also noted to occur with another use as written in the Discord Support section.

**Comment by Jawnb64** [comment]
Same issue, here are my logs. 


[client_2019-08-28.1.log](https://github.com/runelite-extended/runelite/files/3554371/client_2019-08-28.1.log)
[client_2019-08-28.0.log](https://github.com/runelite-extended/runelite/files/3554372/client_2019-08-28.0.log)

**Comment by flewychan** [comment]
Already fixed, please wait for next update

https://github.com/runelite-extended/runelite/issues/1472#issue-486534553
