### ISSUE TITLE
menuentryswapper: login screen shift

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#1480]
when on the login screen, if you push (key down, then key up) the shift key, then login to the game as normal, MES will force 'Walk Here' until you re-push (key down, then key up) the key. maybe Shift to walk/loot is causing this

sam_irl on discord confirmed this was an issue. this will cause issues for people who login with an email as they need to push the @ (shift + 2) for their username

**Comment by Lucwousin** [comment]
Fix would be removing the key listener on login screen / only adding when logged in
