### ISSUE TITLE
RuneLitePlus no longer loading

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite-extended/runelite#1482]
After today's update I am only getting a black screen after starting RuneLitePlus. Runelite loads without problem.

 - OS: Ubuntu 16.04
 - RuneLite version: 1.5.32-SNAPSHOT
 - RuneLitePlus version: 2.1.4.0

Log: https://termbin.com/sp3x

**Comment by xKylee** [comment]
we need to update. be patient.

**Comment by AverageHumanoid** [comment]
It's been 2 hours since the update. RuneLitePlus has always been up before RuneLite for me so I thought this might a problem on my end

**Comment by andrewjmetzger** [comment]
Nope. Issue confirmed, see `#support` on the discord server
