### ISSUE TITLE
Player Indicators 2.1.5.0 'other' option

### ISSUE THREAD

**Issue by Topsy45** [runelite-extended/runelite#1485]
So the option 'other', which highlights all people, overrides friends and clan chat options. ie: People who are normally green/purple due to friends/clan, get overridden to red color if the highlight others option is turned on. It used to work fine prior to this update. edit: work fine as in friends/cc remained green/purple even when the highlight others option was enabled, leaving only non friend/cc members to be highlighted red.

Did not test for other options in that plugin as I only use friend/clan/other options but I'd assume that maybe it overrides them as well.

**Comment by devOSRS** [comment]
+1 I think this PR may have something to do with it https://github.com/runelite-extended/runelite/pull/1437/files

**Comment by pklite** [comment]
fixed in #1524
