### ISSUE TITLE
Freeze Timers still has veng animation warning

### ISSUE THREAD

**Issue by ThatGamerBlue** [runelite-extended/runelite#1486]
The animation stall was removed and it probably never worked anyway.

https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/FreezeTimersOverlay.java#L260

**Comment by xKylee** [comment]
this isnt for anim stall, this is how it detects players who are veng'd or not afaik.

**Comment by pklite** [comment]
fixed in #1544 ? maybe? h
