### ISSUE TITLE
? and % keys not working

### ISSUE THREAD

**Issue by justingerolami** [runelite-extended/runelite#1487]
**Describe the bug**
Used to work fine on old launcher. Few days ago it stopped working, but worked fine on the old jar. Now jar and launcher both won't work. ? and % keys do not work.

**Environment (please complete the following information):**
 - OS: macOS 
- latest runelite+ version of launcher and jar

**Comment by ThatGamerBlue** [comment]
Do you have any hotkeys set to those buttons in any plugins?

**Comment by justingerolami** [comment]
No, they worked fine before and the only thing that changed was client. Works fine on Runelite. Talked to a few other people on discord having the same issue, 2 appear to also be on Mac

**Comment by Ganom** [comment]
Im curious if this could be related to an unset hotkey.

**Comment by ady19980** [comment]
When shift is set as hotkey in MES when typing in game it won't let you type some characters which need shift held like those ones

**Comment by justingerolami** [comment]
> When shift is set as hotkey in MES, typing in game it won't let you type some characters which need shift held like those ones (on mac)

I tried changing it and it didn't solve the issue. Have you gotten the ? to work? I'm able to type using shift fine just not % and ?
