### ISSUE TITLE
PlayerIndicators: Agility icon is jammed right up next to the level and looks bad

### ISSUE THREAD

**Issue by chrisjohnson** [runelite-extended/runelite#1516]
**To Reproduce**
1. Enable player indicators
2. Enable show combat level
3. Enable show agility
4. As icons

**Expected behavior**
Better arrangement

**Screenshots**
![image](https://user-images.githubusercontent.com/178144/64085743-82d2ea00-cd02-11e9-8d1c-89654a23c4fc.png)

![image](https://user-images.githubusercontent.com/178144/64085761-97af7d80-cd02-11e9-80a2-1743db2d7f1e.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by chrisjohnson** [comment]
While I'm looking at the playerindicator plugin, the clan overlay is taking precedence over the friend. 

The order of precedence that I think makes sense is:

* Caller
* Friend
* Clan
* Attackable
* Other

**Comment by jjfishbeck44** [comment]
Caller
Friend
Clan
Attackable
Other
Targets

bring back the option to only enable *allow only in wilderness. Yes/No checkbox
^^ i do not care about "others" outside of wilderness, and it seems that attackable is always breaking as i do not want a player to be highlighted as "target" if being followed or traded. 
 i think a "target" would only be labeled as a player being attacked by your "caller" or a person that majority of your clan is attacking.
