### ISSUE TITLE
blackjack plugin completely broken

### ISSUE THREAD

**Issue by QGoh** [runelite-extended/runelite#1521]
left-clicking sometimes attacks the thug instead of knocking-out or pick-pocketing

**Environment (please complete the following information):**
 - OS: windows
 - RuneLite version: 2.1.5.0

**Comment by QGoh** [comment]
ok for some reason this only happens when i'm using ahk to remap my left click to a key on my keyboard. probably an issue on my side.

**Comment by ThatGamerBlue** [comment]
Duplicate of #1414
