### ISSUE TITLE
Player Scouter spam

### ISSUE THREAD

**Issue by XxVandomxX** [runelite-extended/runelite#1580]
Hello, the player scouter is an awesome feature, however even when ignore friend/clan members is checked, if you hop or someone logs in it will ping them to your discord server regardless of who they are. This causes an unnecessary amount of spam in the discord channel, which is counter productive as it then becomes difficult to find the right information.

**Comment by xKylee** [comment]
nothing we can do about that, that is due to RS not loading your friends/cc list.

**Comment by jjfishbeck44** [comment]
Any chance to condense the 1 page long text message into a shorter and sweet version ? 

When searching for certain clans, all I really wanna know is 
#of attackable players, #skulled, #unskulled 
#world, location, wilderness level range 
 
Or even better yet, having the ability to check box items you want reported back to the discord would be sick. But I'd rather have just 2 line items with less details rather then a page long message on 1 venny player
