### ISSUE TITLE
Add a pray flick option to NPC status timers

### ISSUE THREAD

**Issue by iGuccii** [runelite-extended/runelite#1591]
Please could you include a prayer tab overlay in the "npc status timers" plugin

Would be very useful for slayer if wanting to preserve p pots and don't want to mess around with metronome etc.

**Comment by Ganom** [comment]
npcManager.getStats() can only go so far, we cannot determine if they swap attack styles or not, so the solution to this would be half-assed, or way too complex to be necessary.
