### ISSUE TITLE
1.5.33 shows bank tag items, 1.5.34 doesn't

### ISSUE THREAD

**Issue by Swaiid** [runelite-extended/runelite#1628]
Built 1.5.34, I can see bank tags on items but when I click on the tabs, the items don't appear, however on 1.5.33 they're showing normally.

**To Reproduce**
Open 1.5.34 snapshot and open a tab on the left, no items will appear, do the same on 1.5.33 and they will appear.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 2.1.5.0
 - Launcher version: 1.5.34-SNAPSHOT

**Comment by SRLJustin** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/1625140/65330729-9a650a80-dbfe-11e9-8cc4-59baba8877d7.png)
![image](https://user-images.githubusercontent.com/1625140/65330733-9e912800-dbfe-11e9-89a0-222d0000c7f9.png)

**Comment by Swaiid** [comment]
> 
> 
> Unable to replicate
> 
> ![image](https://user-images.githubusercontent.com/1625140/65330729-9a650a80-dbfe-11e9-8cc4-59baba8877d7.png)
> ![image](https://user-images.githubusercontent.com/1625140/65330733-9e912800-dbfe-11e9-89a0-222d0000c7f9.png)

Strange, I will try remove and add a tag to an item and see if it makes a difference

**Comment by Swaiid** [comment]
![](https://i.gyazo.com/6ed395008f01bd8e930e5d1e52ca8a37.png)
![](https://i.gyazo.com/3f040ce6286be0338457b75c8021773a.png)

No luck

**Comment by Swaiid** [comment]
Simply recompiled and it seems to be working now.
