### ISSUE TITLE
AOE Warnings - CoX Lizardman Shamans incorrect area

### ISSUE THREAD

**Issue by GrimWrath** [runelite-extended/runelite#195]
CoX Shamans have a 3x3 marker shown in AOE warnings when their poison splat is actually 4x4.

**Comment by Ganom** [comment]
Is this true for other shamans, or just cox?

**Comment by Ganom** [comment]
Fixed in https://github.com/runelite-extended/runelite/pull/196

**Comment by farhan1666** [comment]
it's 5x5 not 4x4
