### ISSUE TITLE
Overlay error

### ISSUE THREAD

**Issue by james-munson** [runelite-extended/runelite#22]
Friend got this overlay error then it went away, just making this git issue just in case we come across it again.

2019-04-21 02:09:50 [Client] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: null

http://prntscr.com/neqc7c

**Comment by renewablezip01** [comment]
Just some further info, i got that error when i was manually casting spells from my spellbook on players in the wild, this is the error code http://prntscr.com/neqd5a

**Comment by Ganom** [comment]
So i'm going to assume this has to do with how freeze timers adds targets to an array from menu entry generation?

**Comment by renewablezip01** [comment]
> So i'm going to assume this has to do with how freeze timers adds targets to an array from menu entry generation?

Not quite sure but at that moment of time i was casting fire wave, all though it works on other spells such as fire blast

**Comment by james-munson** [comment]
i think this was fixed?
