### ISSUE TITLE
License issue with prayeralert plugin

### ISSUE THREAD

**Issue by lachlan-smith** [runelite-extended/runelite#227]
Hello RuneLitePlus,

I have noticed that you are using code from a project I am a part of called "prayeralert" - [https://github.com/lachlan-smith/prayeralert](https://github.com/lachlan-smith/prayeralert) in your client. I'm glad to see you think the plugin is useful and I have licensed it under the GNU General Public License v3.0 to allow projects such as yours to utilize my work.

However, I noticed some issues with your implementation of my code which are required to meet the licensing requirements. You have removed my original license file from and have placed your own license in the header of each of my files (PrayerAlertConfig.java, PrayerAlertOverlay.java and PrayerAlertPlugin.java). 
The license you have included also appears not to be the GPLv3 license my work is licensed under. This is not allowed under the GPLv3 license and my code base must stay licensed as GPLv3. To help you fix this problem, I have updated my original repository with the correct headers in each file for you to utilize, however you will also need to include a full copy of the GPLv3 license with my plugin.

If you could take care of these issues for me, that would be greatly appreciated. 

Kind Regards,
lachlan-smith

**Comment by zeruth** [comment]
I'll make sure that gets taken care of today :)

**Comment by Kyleeld** [comment]
Sorry about that bud, the original code we had was
From another repo with no header file. We added ours into give it a licence, not to remove credit where it’s due. I’ve changed this and put in a PR requested to fix this up :)
