### ISSUE TITLE
Chambers of Xeric - Level time tooltip does not show

### ISSUE THREAD

**Issue by GrimWrath** [runelite-extended/runelite#287]
Chambers of Xeric plugin - When ticked, the level time tooltip does not show anywhere.

**To Reproduce**
Using these settings: https://i.vgy.me/3152zm.png

**Expected behavior**
Level time tooltip to show as a buff icon, similar to vanilla runelite chambers plugin.

**Screenshots**
https://i.vgy.me/3152zm.png

**Environment (please complete the following information):**
Latest runelite+ jar as of 5/17/19

**Comment by Ganom** [comment]
Fixed in https://github.com/runelite-extended/runelite/pull/288
