### ISSUE TITLE
Slayer icon missing for Alchemical Hydra

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#290]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When you have Alchemical Hydra as your slayer task, the infobox doesn't show any icon

**To Reproduce**
Have Alchemical Hydra as your slayer task and have slayer infoboxes on

**Expected behavior**
The Alchemical Hydra should be shown in the infobox

**Screenshots**
https://i.imgur.com/JXVDjFn.png

**Environment (please complete the following information):**
https://i.imgur.com/R8KpIoA.png

**Comment by Ganom** [comment]
Is it missing in default runelite aswell?

**Comment by SRLJustin** [comment]
No it's not.

https://i.imgur.com/hir6Wj5.png

**Comment by Lucwousin** [comment]
This happens sometimes and also happens on runelite
