### ISSUE TITLE
Menu Entries not being fully removed in Clan Man Mode

### ISSUE THREAD

**Issue by Ganom** [runelite-extended/runelite#292]
**Describe the bug**
Attack option not being fully removed for some reason.

**To Reproduce**
Enable clan man mode
Enable remove attack on clan members.

**Expected behavior**
Attack option fully removed.

**Screenshots**
https://streamable.com/lui79

**Comment by Kyleeld** [comment]
does PVP tools do the same also?

**Comment by Lucwousin** [comment]
I think that's on purpose so if you get bs'd you can still fight back

**Comment by pklite** [comment]
if it works like PvP tools one, it changes onMenuEntryAdded so it wouldn't update until a new menu entry gets added

**Comment by Lucwousin** [comment]
That's every frame :P
