### ISSUE TITLE
Easyscape skills necklace swap not fully working

### ISSUE THREAD

**Issue by ocekyled** [runelite-extended/runelite#332]
**Describe the bug**
Skills necklace swapper not swapping woodcutting or farming guild

**To Reproduce**
Equip Skills Necklace
Change Easyscape/Jewellery swapper/Swap Skill to either Woodcutting or Farming Guild
Check Inventory Screen

**Screenshots**
https://i.imgur.com/omk5kwO.gifv

**Comment by Ganom** [comment]
What are the exact names of the teleport in the right click menu?

**Comment by ocekyled** [comment]
https://i.imgur.com/xxRHNtc.png

**Comment by Ganom** [comment]
Hmm, thats quite odd, the enums are identical.

Thanks for reporting this.

**Comment by Lucwousin** [comment]
To fix things like this, make sure not to only swap the entries, but also swap the types (one of them will be 1007, other 57)

**Comment by Lucwousin** [comment]
Fixed in #351
