### ISSUE TITLE
EZSCAPE Construction not working

### ISSUE THREAD

**Issue by SeaSlash** [runelite-extended/runelite#350]
When construction is enabled on Ezscape it shows Examine instead of Build/Remove. Worked perfectly fine yesterday. No changes made on my end.

**Comment by Ganom** [comment]
Can you show a screenshot of your easyscape settings?

**Comment by SeaSlash** [comment]
https://i.imgur.com/cnYn7n4.png

**Comment by Ganom** [comment]
This should be fixed in https://github.com/runelite-extended/runelite/pull/364

**Comment by Ganom** [comment]
Still bugged

**Comment by zpar-ky** [comment]
Enabling this for oak larders (15403) freezes the game and I have to force close
