### ISSUE TITLE
TMorph how to use? ID?

### ISSUE THREAD

**Issue by kaffeknugen** [runelite-extended/runelite#353]
As the title says. Have tried using id for infernal cape. And my graceful id as cape that im wearing. Nothing happens. How do i use this plugin? Looks really cool

**Comment by Ganom** [comment]
Cloak would be infernal, target would be graceful cape, make sure thats correct.

**Comment by kaffeknugen** [comment]
Cloak doesnt exist. I only have cape to use. And yes. In Melee swap i have cape id 21295 and i have tried all different kind of ID's. And i have on target melee swap cape ID 13617 which is the correct ID of the cape that im wearing. Found the ID thru Devtools inverntory option.

But it doesnt do anything.

**Comment by Ganom** [comment]
Graceful cape is incorrect in dev tools it seems, 11853 is the correct id.

**Comment by kaffeknugen** [comment]
I have the red graceful cape

**Comment by kaffeknugen** [comment]
https://gyazo.com/8bd24c401878cf87530a1a3cefff914b

**Comment by Ganom** [comment]
Try 13618

**Comment by kaffeknugen** [comment]
IT WORKED DAMN
NICE MAN THANKS!

**Comment by Ganom** [comment]
Yeah, for some reason dev tools is grabbing wrong id for those.
