### ISSUE TITLE
Plugin Rework/Move

### ISSUE THREAD

**Issue by Kyleeld** [runelite-extended/runelite#38]
**SO, at present these are a list of non OEM plugins:**

> AntiDrag
> AOEWarnings
> BA Tools
> Blackjacking
> ClanManMode
> EquipmentInspector
> FightCaveJadHelper
> FightCaveWaveHelper
> FreezeTimers
> HidePrayers
> Hydra
> InventoryViewer
> KittenNotifier
> LizardmenShaman
> LootingBagViewer
> MultiIndicators
> PlankMaker
> PlayerIndicators
> PrayAgainstPlayer
> Profiles
> PVPTools
> PyramidPlunder
> Raids
> RaidsTheiving
> RememberClan
> ShayzianInfirmary
> ShiftWalker
> SlayerMusiq
> Smelting
> Spellbookfixer
> Stronghold
> TempleTrek
> TickCounter
> Timers (skull timer)
> TOB
> TOBDamageCount
> Vanguards
> Vetion
> Vorath
> WarIndicators
> WhaleWatchers
> WildernessLocations
> WorldMapHider
> Zulrah

**these are what I would consider OP, and worth moving to the private REPO:**
> AOEWarnings
> Blackjacking
> FreezeTimers
> Hydra
> LizardmenShaman
> LootingBagViewer
> PrayAgainstPlayer
> Raids
> RaidsTheiving
> TOB
> TOBDamageCount
> Vanguards
> Vetion
> Vorath
> Zulrah

**these are what I would consider as worth just removing completely:**
> PlankMaker
> SlayerMusiq
> Stronghold
> TempleTrek

**these are what I would consider as fine to keep in the current repo:**
> AntiDrag
> BA Tools
> ClanManMode
> EquipmentInspector
> FightCaveJadHelper
> FightCaveWaveHelper
> HidePrayers
> InventoryViewer
> MultiIndicators
> PlayerIndicators
> Profiles
> PVPTools
> PyramidPlunder
> RememberClan
> ShayzianInfirmary
> ShiftWalker
> Smelting
> TickCounter
> Timers (skull timer)
> WarIndicators
> WhaleWatchers
> WildernessLocations
> WorldMapHider

**and this is what i would consider as NWAE (not working as expected) and can be removed until fixed:**
> KittenNotifier
> SpellbookFixer

**Comment by renewablezip01** [comment]
Spellbookfixer is working fine. Though the kittennotifier when i tried it, it made the client freeze and stop working until i disable it and re ran the client

**Comment by james-munson** [comment]
we will discus on discord some more.
