### ISSUE TITLE
Flash while idle

### ISSUE THREAD

**Issue by Coollegolas** [runelite-extended/runelite#384]
Hey, I hope this is the right place - came from #suggestions. 

I'm wondering if it'd be possible to expand the "Idle Alerts" modlet in some way to include an option for it to just keep flashing red on your screen as long as your character remains idle?

It'd be useful for alt-scape where you're fishing or woodcutting/etc and lose track of which account you're supposed to be looking at.

If I've just missed a feature or this is the wrong place, please feel free to tell me to piss off.

Thanks for all your hard work.

**Comment by Ganom** [comment]
This was added to base runelite.
