### ISSUE TITLE
Menu Entry Swapper - Spiritual Fairy Tree POH

### ISSUE THREAD

**Issue by Galtiak** [runelite-extended/runelite#397]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The left click option on the spiritual fairy tree is changed from

Tree Spiritual Fairy Tree,

to

Ring-last-destination Spiritual Fairy Tree,

when the plugin is switched on. However, there is no tick box to disable this change. (I confirmed this by unticking everything and switching the plugin on and off, the entry still changes.)

**To Reproduce**
1. Go to your POH.
2. Click on the tree, with Menu Entry Swapper disabled and notice the first option is 'tree'
3. Enable Menu Entry Swapper, but disable all of the options and notice the first option is 'Ring-last-destination'.

**Expected behavior**
I expect this option to not change when everything is unticked in the menu entry swapper plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/18116850/58386369-b06b1180-7ff6-11e9-8361-858305ef5821.png)

![image](https://user-images.githubusercontent.com/18116850/58386370-b4972f00-7ff6-11e9-83d9-d46a465b8441.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10
 - RuneLite version: [e.g 1.4.6] 1.5.25-SNAPSHOT
 - Launcher version: [e.g 1.5.2] UNKNOWN

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Kyleeld** [comment]
the option for this is under "Teleportation"
