### ISSUE TITLE
Easy Construction not working correctly.

### ISSUE THREAD

**Issue by Rn3333** [runelite-extended/runelite#400]
Not sure if it's a bug or if I'm doing something wrong. When easy construction is enabled in menu entry swapper, the menu options change but don't work correctly. Using it on the Mythical Cape decoration, clicking "build" does nothing. Clicking "remove" will teleport you to the Myths' Guild and clicking "teleport" will remove the decoration.

I was using IDs "15394, 31986"

 - OS: Windows
 - RuneLite version: 1.5.25
 - Launcher version: 1.6.3

**Comment by inadquatecoding** [comment]
using ID 13566 menu swapper also doesn't work with oak larders. It shows "remove" but clicking on the larder just searches it.

**Comment by adrian089089** [comment]
> using ID 13566 menu swapper also doesn't work with oak larders. It shows "remove" but clicking on the larder just searches it. When the menu entry swapper is turned off remove becomes "search" and "search" becomes remove.
> 
> * ```
>   OS: Windows
>   ```
> * ```
>   RuneLite version: 1.5.25
>   ```
> * ```
>   Launcher version: 1.6.3
>   ```

I'm also experiencing this

**Comment by 84lemmings** [comment]
remove for mahogany tables with id 13298 does nothing when left or right clicked

**Comment by Ganom** [comment]
Fixed in https://github.com/runelite-extended/runelite/pull/442
