### ISSUE TITLE
Freeze timers work in PVP but dont register in PVE

### ISSUE THREAD

**Issue by 369lo** [runelite-extended/runelite#418]
**Describe the bug**
With Freeze timers and all settings enabled, it clearly shows up in PVP, but not in PVE scenarios

**To Reproduce**
1. Go to 'freeze timers'
2. Click on 'show npc, show freeze timers'
3. cast a freeze on an npc
4. no overlay

**Expected behavior**
gives an overlay like in PVP situations such as in picture 1

**Screenshots**
![pvp](https://i.imgur.com/CCySm2p.png)

![pvm](https://i.imgur.com/w6KAA6E.png)

![settings](https://i.imgur.com/7kCUuHn.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: [1.5.25-snapshot]
 - Launcher version: [1.6.3-snaphsot]

**Comment by Kyleeld** [comment]
@MarruhK is working on this.
