### ISSUE TITLE
java.lang.IllegalArgumentException in experiencedrop plugin

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#422]
Fresh pull from github, throwing errors when loading any new region ingame; below is the output

https://gist.github.com/SRLJustin/3f50c5468ec52c357352f4cc7ebac9ac

**Comment by SRLJustin** [comment]
After toggling the 'Show Damage on XP Drop' settings from `None` to `In Xp Drop` back to  `None` stops the errors being thrown

**Comment by kevinf100** [comment]
This setting use to be a Boolean, but it was change to be strings. If you ran RL+ before this change (non-github) and run it after this change (github build) it gets an unexpected value of true or false. Changing the setting overwrites the true or false values there.
