### ISSUE TITLE
Vorkath Random Tile Markers

### ISSUE THREAD

**Issue by Galtiak** [runelite-extended/runelite#424]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
There are random purple tile markers being placed around the map while at vorkath.

**To Reproduce**
1. Go to Vorkath island with Vorkath Helper enabled.

**Expected behavior**
No random purple tile markers.

**Screenshots**
![image](https://user-images.githubusercontent.com/18116850/58493328-9a7e5d80-816a-11e9-9f83-840537a789e3.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Ganom** [comment]
That is the safe spot plugin I do believe

**Comment by Galtiak** [comment]
> That is the safe spot plugin I do believe

ill give it a test
