### ISSUE TITLE
Mining plugin not working

### ISSUE THREAD

**Issue by fatchan** [runelite-extended/runelite#433]
The mining plugin doesnt show anything when enabled.

Expected it to show some information similar to the woodcutting plugin:
![image](https://user-images.githubusercontent.com/18641559/58536445-e9dc9080-8233-11e9-9e01-32fe0d339eba.png)

Cheers.

**Comment by james-munson** [comment]
Read what the mining plugin actually does under the config

**Comment by fatchan** [comment]
![image](https://user-images.githubusercontent.com/18641559/58537127-979c6f00-8235-11e9-9376-5ad86d5a6241.png)
![image](https://user-images.githubusercontent.com/18641559/58537133-9a975f80-8235-11e9-8d87-03f5392e9b8d.png)
Yep, session stats not working. But whatever, close the issue :roll_eyes:

**Comment by james-munson** [comment]
Sorry was not aware this mining plugin had session stats as well, this plugin most likely will get some work on it soon.

**Comment by Ganom** [comment]
This was probably broken in the update, due to jagex removing and readjusting a ton of gameobject ids, and the creator of the plugin didn't grab from api, and instead hard coded the ids in, it'll take quite a bit of work to get it back up and running.
