### ISSUE TITLE
Custom swap for tarns lair/Rogues den

### ISSUE THREAD

**Issue by WatWeDoin** [runelite-extended/runelite#477]
So instead of having to right click all the little traps in tarns lair/rogues den instead you could have it swapped to left click instead https://i.imgur.com/X6gsMII.png

**Comment by Grabbin** [comment]
But you just skip over all the traps anyway don't you?

**Comment by tomcylke** [comment]
Pretty sure you can skip all of them in Rogue's Den but the right click jumps in Tarn's Lair can't be skipped.
