### ISSUE TITLE
Vorkath melee attacks don't increase counter 

### ISSUE THREAD

**Issue by Tdarnell** [runelite-extended/runelite#478]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Vorkaths 5 attack counter doesn't increase when hit by melee attacks. 

**To Reproduce**
1. Get hit by Vorkath in melee range

**Expected behavior**
Increase the overhead counter by 1

**Environment (please complete the following information):**
 - Windows
- RuneLite version: 1.5.26-SNAPSHOT
- Launcher version: 1.6.3-SNAPSHOT
- RuneLitePlus version: RuneLite Plus 1.4

**Comment by FrostyFridge** [comment]
Just tested this, it's fixed. Probably by https://github.com/runelite-extended/runelite/commit/c15c93f5e53b9335fd992be55279d9c790514293
