### ISSUE TITLE
Log out of one account and back into another, one click.

### ISSUE THREAD

**Issue by conquerDMM** [runelite-extended/runelite#479]
**Is your feature request related to a problem? Please describe.**
Often play multiple accounts, annoying to log in even with current account switcher plugin.

**Describe the solution you'd like**
I would like to be able to completely switch accounts and login to a new one with one click.

**Describe alternatives you've considered**
Current plugin works, but would be a nice to have.

**Additional context**
Essentially switch between accounts with one click, kind of like you do for hopping worlds

**Comment by Ganom** [comment]
Not possible without automation.
