### ISSUE TITLE
Pk'd calculator in chatbox

### ISSUE THREAD

**Issue by Gemeinerik** [runelite-extended/runelite#495]
a pk'd loot calculator? Basicly what Exilent has, so maybe winnetou is willing to help out? 

E.G:
https://gyazo.com/2306550530d31fbccd9f600588d29e4e @

**Comment by Kyleeld** [comment]
i like the suggestion, we shall look into it.

**Comment by sdburns1998** [comment]
What's the benefit of this over the loottracker that shows all items and the amount you PK'd?
