### ISSUE TITLE
Add the friendly and enemy player counter from pvp tools as an indicator.

### ISSUE THREAD

**Issue by Levy2** [runelite-extended/runelite#497]
**Is your feature request related to a problem? Please describe.**
Currently a counter for friendly and enemy players exists in the pvp tools. This is however hidden in the pvp tools tab which means I can't leave my loot tracker open during pk trips.
This is the current feature: 
![image](https://user-images.githubusercontent.com/47631634/58882159-ef2a5700-86db-11e9-9849-d661d7ce8295.png)

**Describe the solution you'd like**
I would like if a toggleable indicator for the enemy and friendly player counter would be implemented. Something like this: 
![image](https://user-images.githubusercontent.com/47631634/58882144-e9cd0c80-86db-11e9-892a-73f597cf094f.png)

This way I know how many numbers the enemy has and I can leave my loot tracker open.

**Comment by vindux** [comment]
That could be pretty useful to see numbers without having to have the panel open
