### ISSUE TITLE
Menu Entry Swapper Capes

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite-extended/runelite#499]
- Swap Ardougne Cape option should also apply to Ardougne max cape
- Add option for Music cape
- Add option for Achievement diary cape

**Comment by Kyleeld** [comment]
can you provide the EXACT name of all of the capes (with correct capitalisation) along with a list of their right click options (with correct capitalisation) and what you want them to be swapped to? @AverageHumanoid

**Comment by AverageHumanoid** [comment]
- Ardougne max cape - ID 20760
- Music cape - ID 13221
- Music cape(t) - ID 13222
- Achievement diary cape - ID 19476
- Achievement diary cape(t) - ID 13069

Swap "Wear" with "Teleport" while in inventory and "Remove" with "Teleport" in equipment interface

In inventory from

- Wear
- Teleport
- Use
- Trim/Untrim
- Drop
- Examine
- Cancel

to

- Teleport
- Wear
- Use
- Trim/Untrim
- Drop
- Examine
- Cancel

In equipment interface from

- Remove
- Trim/Untrim
- Teleport
- Examine
- Cancel

to 

- Teleport
- Trim/Untrim
- Remove
- Examine
- Cancel

**Comment by AverageHumanoid** [comment]
There are other capes with teleport options that can be added to the Equipment swapper section of Menu Entry swapper including the Quest point cape, Farming cape, Strength cape.

**Comment by Ganom** [comment]
This can be achieved with custom swaps now.
