### ISSUE TITLE
(PvP) Allied players still attackable in left-click menu.

### ISSUE THREAD

**Issue by Yeet2018** [runelite-extended/runelite#514]
With clan man mode and player indicators opinion to hide 'attack' from allied players you can still left-click attack since a couple patches ago.

![2019-06-06_11-54-01](https://user-images.githubusercontent.com/44622559/59048157-456dd600-8853-11e9-9aea-b4a64ab2f65d.png)
![2019-06-06_11-54-04](https://user-images.githubusercontent.com/44622559/59048165-47d03000-8853-11e9-88ee-22182d715ab7.png)

**Comment by Ganom** [comment]
Fixed https://github.com/runelite-extended/runelite/pull/505
