### ISSUE TITLE
Screen is tessellated 

### ISSUE THREAD

**Issue by Nonamespazz** [runelite-extended/runelite#525]
Just downloaded the runelite client today, for linux. Im running it on ubuntu 18.1 on a old dell optiplex. Everytime i open the client, I get this:
![image](https://user-images.githubusercontent.com/51502070/59142512-79e5ad00-898d-11e9-89ee-1a459513510f.png)

According to the logs, the client is running fine. The audio works, and the screen even moves normally, just in those tiny copied squares. Obviously logging in is impossible though. 

Any help would be greatly appreciated, happy to add more info if you need it.

**Comment by Lucwousin** [comment]
Disable hardware accel
https://github.com/runelite-extended/runelite/wiki/Disable-Hardware-Acceleration
