### ISSUE TITLE
CoX scouter enhancements

### ISSUE THREAD

**Issue by farhan1666** [runelite-extended/runelite#532]
1) Indicate whether the crabs in the raid is good crabs or bad crabs in the scouter:
Crabs are good crabs if:
Good crabs:
In - SFCCS PCPSF - The crabs have to be the second puzzle
In - SCSPF CCSPF - The crabs can be in both places, both of them are good.
In - SCPFC CSPSF - The crabs have to be the second puzzle.
In - FSCCS PCPSF - The crabs have to be the second puzzle

2) Notify you in some way if the raid you scouted is the record rotation (Vasa Tekton Vespula Good Crabs Tightrope) as for the average raider it is significantly more profitable to sell the scout instead of doing it as world record teams will pay anywhere from 5m to 50m depending on the time. Maybe make the scouter background green with a meaningful message in chat.

**Comment by farhan1666** [comment]
Crabs can be one of 3 layouts, good crabs, bad crabs and one I like to call rare crabs because it does not appear in any 3 combat layouts which I mostly do hence I rarely see it. here is a list of conditions for the crab layout for every raids layout:
"FSCCP.PCSCF - #WNWSWN#ESEENW", //both good crabs
"FSCCS.PCPSF - #WSEEEN#WSWNWS", //bad crabs first good crabs second
"FSCPC.CSCPF - #WNWWSE#EENWWW", //bad crabs first rare crabs second
"SCCFC.PSCSF - #EEENWW#WSEEEN", //bad crabs
"SCCFP.CCSPF - #NESEEN#WSWNWS", //both bad crabs
"SCFCP.CCSPF - #ESEENW#ESWWNW", //bad crabs first good crabs second
"SCFCP.CSCFS - #ENEESW#ENWWSW", //good crabs
"SCFCPC.CSPCSF - #ESWWNWS#NESENES", //both bad crabs
"SCFPC.CSPCF - #WSWWNE#WSEENE", //good crabs first rare crabs second
"SCFPC.PCCSF - #WSEENE#WWWSEE", //bad crabs first rare crabs second
"SCFPC.SCPCF - #NESENE#WSWWNE", //bad crabs first rare crabs second
"SCPFC.CCPSF - #NWWWSE#WNEESE", //both rare crabs
"SCPFC.CSPCF - #NEEESW#WWNEEE", //rare crabs first good crabs second
"SCPFC.CSPSF - #WWSEEE#NWSWWN", //bad crabs first good crabs second
"SCSPF.CCSPF - #ESWWNW#ESENES", //both good crabs
"SFCCP.CSCPF - #WNEESE#NWSWWN", //bad crabs first rare crabs second
"SFCCS.PCPSF - #ENWWSW#ENESEN", //bad crabs then good crabs
"SPCFC.CSPCF - #WWNEEE#WSWNWS", //both good crabs
"SPCFC.SCCPF - #ESENES#WWWNEE", //bad crabs first good crabs second
"SPSFP.CCCSF - #NWSWWN#ESEENW", //bad crabs first good crabs second
"SCFCP.CSCPF - #ENESEN#WWWSEE", //both bad crabs
"SCPFC.PCSCF - #WNEEES#NWSWNW", //rare crabs first bad crabs second
"SFCCPC.PCSCPF - #WSEENES#WWWNEEE", //good crabs first rare crabs second rare crabs third
"FSPCC.PSCCF - #WWWSEE#ENWWSW", //both bad crabs
"FSCCP.PCSCF - #ENWWWS#NEESEN", //bad crabs first good crabs second
"SCPFC.CCSSF - #NEESEN#WSWWNE", //good crabs

If a layout is "//bad crabs first good crabs second" that means that if crabs were the first puzzle room, it would be bad crabs however if it were the second puzzle room it would be good crabs.

**Comment by Ganom** [comment]
Are those the string outputs for the scouter?

**Comment by farhan1666** [comment]
Sorry, care to elaborate on what you mean, this is what I found in LayoutSolver.java, I just added the comments on the end specifying what type of crabs

**Comment by Ganom** [comment]
```plugin.getRaid().getLayout().toCodeString()```

This code will give you the code strings that are compatible with the scouter.

**Comment by farhan1666** [comment]
Oh, no these aren't but can be very easily:
"FSCCPPCSCF", //both good crabs
"FSCCSPCPSF", //bad crabs first good crabs second
"FSCPCCSCPF", //bad crabs first rare crabs second
"SCCFCPSCSF", //bad crabs
"SCCFPCCSPF", //both bad crabs
"SCFCPCCSPF", //bad crabs first good crabs second
"SCFCPCSCFS", //good crabs
"SCFCPCCSPCSF", //both bad crabs
"SCFPCCSPCF", //good crabs first rare crabs second
"SCFPCPCCSF", //bad crabs first rare crabs second
"SCFPCSCPCF", //bad crabs first rare crabs second
"SCPFCCCPSF", //both rare crabs
"SCPFCCSPCF", //rare crabs first good crabs second
"SCPFCCSPSF", //bad crabs first good crabs second
"SCSPFCCSPF", //both good crabs
"SFCCPCSCPF", //bad crabs first rare crabs second
"SFCCSPCPSF", //bad crabs then good crabs
"SPCFCCSPCF", //both good crabs
"SPCFCSCCPF", //bad crabs first good crabs second
"SPSFPCCCSF", //bad crabs first good crabs second
"SCFCPCSCPF", //both bad crabs
"SCPFCPCSCF", //rare crabs first bad crabs second
"SFCCPCPCSCPF", //good crabs first rare crabs second rare crabs third
"FSPCCPSCCF", //both bad crabs
"FSCCPPCSCF", //bad crabs first good crabs second
"SCPFCCCSSF", //good crabs

**Comment by Ganom** [comment]
If those are the same as the getlayout.tocode then it should be quite easy to implement.

**Comment by farhan1666** [comment]
🎉

**Comment by farhan1666** [comment]
The only weird part is treating the same puzzle differently if its in a different part of the layout, currently nothing similar is done but it shouldn't be too much of a challenge

**Comment by farhan1666** [comment]
What about the record layout identification, is that something you guys would be willing to put in, there are always buyers for these scouts and they are very commonly thrown away by junior raiders who don't wanna do all the harder bosses in raids not knowing the scout is worth ludicrous amounts of money.

**Comment by Ganom** [comment]
Yeah, just gimmie the code.
