### ISSUE TITLE
Left-click priority

### ISSUE THREAD

**Issue by luddeb123** [runelite-extended/runelite#542]
Prioritize left click on the Saradomin boss instead of having to right-click both minion and zily to then click on Zily. preferably would leftclick still work on minion when boss is not leftclickable. just make zily prio over minion.

**Comment by SRLJustin** [comment]
This can be done with Custom Swaps

untested but should work:
``
Attack,Bree:Attack,Commander Zilyana
Attack,Starlight:Attack,Commander Zilyana
Attack,Growler:Attack,Commander Zilyana
``

**Comment by Kyleeld** [comment]
as above.
