### ISSUE TITLE
Spec Bar In Wildy 

### ISSUE THREAD

**Issue by GoMSaja** [runelite-extended/runelite#547]
The spec bar is not usable when entering in a pvp area place. It says "The orb does not control special attacks in PvP areas". How do i turn this off. I want to be able to use the spec bar even in wildy

**Comment by Lucwousin** [comment]
If by spec bar you mean spec orb that's impossible

**Comment by ThatGamerBlue** [comment]
@Lucwousin this actually sounds like a bug with the spec bar client script mod, I'm reopening

**Comment by GoMSaja** [comment]
Yeah the spec orb. I don't want it when im using it in wildy. Haha

**Comment by Lucwousin** [comment]
Yeah it's not an issue with the script then, but just a limitation jagex put in. It checks if you're in wildy both client side and server side
