### ISSUE TITLE
Runecraft Plugin Bug

### ISSUE THREAD

**Issue by Failed4life** [runelite-extended/runelite#553]
**Describe the bug**
When Runecraft plugin is enabled, it does not matter what settings are checked, the Craft-rune option on the runecrafting altars is not there, also Pure Essence left click is examine and there is no use option.

**To Reproduce**
Enable Runecraft plugin, try to craft runes.

**Expected behavior**
Click on altar to craft runes

**Screenshots**
https://i.imgur.com/99ox17c.png

**Comment by Failed4life** [comment]
Heres a gif https://i.imgur.com/UQomAoU.gifv

**Comment by ocekyled** [comment]
Turning off the "Lavas" option in the runecrafting config should fix this for you.
It's there to prevent crafting the wrong runes when doing combination runes.
https://i.imgur.com/qbfX59N.gifv

**Comment by Failed4life** [comment]
> Turning off the "Lavas" option in the runecrafting config should fix this for you.
> It's there to prevent crafting the wrong runes when doing combination runes.
> https://i.imgur.com/qbfX59N.gifv

Thanks for your reply, yes, this does seem to work, but it seems that it is still bugged since it requires turning off/on the entire plugin rather than just the "Lavas" option. https://i.imgur.com/bkG2ibZ.gifv

**Comment by Ganom** [comment]
Is this still occurring?
