### ISSUE TITLE
Menu Quantities not shown properly for some items

### ISSUE THREAD

**Issue by bigmemes420** [runelite-extended/runelite#556]
**Describe the bug**
Ground items are not showing quantity in the context menu (Things like runes/coins)
**To Reproduce**
Drop an item that's stackable (IE: Chaos runes) 

**Expected behavior**
Should show quantities

**Screenshots**
https://i.imgur.com/hyi24Ry.png

**Comment by Ganom** [comment]
Is this still happening?

**Comment by bigmemes420** [comment]
It seems to be fixed now
