### ISSUE TITLE
Slayer Kills left count not updating

### ISSUE THREAD

**Issue by bigmemes420** [runelite-extended/runelite#557]
**Describe the bug**
Sometimes the slayer kill counter doesn't update properly (specifically in this case kraken boss, could be others)

**To Reproduce**
1. Get a slayer task
2. Kill the target for the task

**Expected behavior**
Should count per kill you get as before.

**Comment by SRLJustin** [comment]
#536

**Comment by SRLJustin** [comment]
Also noticed this for Mutated Zygomites

**Comment by Ganom** [comment]
Can you provide npc ids for all offenders?

**Comment by SRLJustin** [comment]
https://imgur.com/UwGuI5Q

Kraken is my current slayer task, i have slayer targets turned on (should have a npc border around it) once i get the kill, slayer KC doesn't go down until i manually check my slayer helm (i check this at 0.1 on the respawn timer)

(before npc spawned) https://i.imgur.com/xMQmwPs.png
(npc spawning) https://i.imgur.com/vr3kpAw.png
