### ISSUE TITLE
Ice Barrage freeze timer off by 3 seconds

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite-extended/runelite#558]
https://streamable.com/ipprl

**Comment by Kyleeld** [comment]
This included a 3 second countdown for immunity to another freeze.

**Comment by AverageHumanoid** [comment]
How come this is different than Ice blitz?

**Comment by AverageHumanoid** [comment]
What about adding a config option to include or uninclude that additional timer?

**Comment by zpar-ky** [comment]
@AverageHumanoid Edit [this line](https://github.com/runelite-extended/runelite/blob/9dad597c2402ad9998efd1cafa9d2a80fd461f85/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/PlayerSpellEffect.java#L39) from 22200 to 19200 and build it yourself if you really want to
