### ISSUE TITLE
Bandos and minions attack tick counter (WIP) 

### ISSUE THREAD

**Issue by w355osrs** [runelite-extended/runelite#567]
With the infernal plugin release I think a visible tick counter for all of gwd and minions would be a great idea. I also think DKS attack timers would be good too. Graphic IDs constantly change depending on player and npc location. Let me know if anymore information I can research can help! 

Minions attack every 5 ticks. Bandos attacks every 6 ticks. 

General Graardor idle: (ID: 2215 (A: -1) (G: -1)
General Graardor attack animations: 
1) A: 7018 G: -1
2) A: 7019 G: -1
3) A: 7020 G: -1
4) A: 7021 G: 1203

Sergeant Grimspike idle animation: (ID: 2218) (A: -1) (G: -1) 
Sergeant Grimspike attack animations: 
1) A: 6155 G: -1
2) A: 6156 G: -1
3) A: 7073 G: 1219  

Sergeant Steelwill idle: (ID: 2217) (A: -1) (G: -1)
Sergeant Steelwill attack animations: 
1) A: 6154 G: 377
2) A: 6155 G: -1      
3) A: 6156 G: -1
4) A: 7071 G: 1216

Segeant Strongstack idle: (ID: 2216) (A: -1, G: -1)
Sergeant Strongstack attack animations:
1) A: 6154 G: -1
2) A: 6155 G: -1
3) A: 6156 G: -1

**Comment by Ganom** [comment]
👍

**Comment by Ganom** [comment]
Implemented in https://github.com/runelite-extended/runelite/pull/578
