### ISSUE TITLE
The "Runelite" plugin disappears after hiding then unhiding plugins with the organizer

### ISSUE THREAD

**Issue by bigmemes420** [runelite-extended/runelite#569]
**Describe the bug**
After enabling "Hide plugins" in the organizer than turning it off, it will hide the "runelite" plugin unless you search it.
**To Reproduce**
1. In plugin organizer, enable hide plugins
2. Then disable it

**Expected behavior**
Should show the runelite plugin anyways

**Comment by Kyleeld** [comment]
can you confirm it just doesnt appear down the bottom of the list? if it was hidden, you wouldnt be able to find it when searching for it.

**Comment by bigmemes420** [comment]
It appears at the bottom but should always be at the top.
