### ISSUE TITLE
AoE shown at KQ

### ISSUE THREAD

**Issue by bigmemes420** [runelite-extended/runelite#570]
**Describe the bug**
At KQ there is an AoE being shown despite there being no AoE projectile

**To Reproduce**
1. Fight KQ
2. Wait for mage attack

**Expected behavior**
Shouldn't show AoE

**Screenshots**
https://i.imgur.com/WwAl3PH.png

**Comment by Ganom** [comment]
Can you provide the ID of the offending attack?

**Comment by bigmemes420** [comment]
It would be 280

**Comment by Ganom** [comment]
Odd, so thats the same ID as vetions lightning
