### ISSUE TITLE
Disabling plugin organizer removes colours but doesn't reorder correctly

### ISSUE THREAD

**Issue by Lucwousin** [runelite-extended/runelite#575]
Disabling plugin organizer removes the colours but still keeps the plugins grouped, instead of sorting by name again

**Comment by zeruth** [comment]
Make changes here, this is where the grouping is done: 
![image](https://user-images.githubusercontent.com/2943260/59477268-75ecdb80-8e22-11e9-9e37-977ef3bf97c1.png)
