### ISSUE TITLE
Chambers of Xeric - Some opponent hitpoints remains at 0 

### ISSUE THREAD

**Issue by p00boy** [runelite-extended/runelite#582]
Applies only to certain npcs (like skeletal mystics and shamans),

**Comment by Ganom** [comment]
I assume this has to do with them having incorrect NPC Definition information, if you could provide all the IDs of the offenders, we can take a look.

**Comment by xperiaclash** [comment]
skeletal mystic 7604-7605-7606
I believe tightrope monsters have this issue too, I'll get their ids soon enough

**Comment by Ganom** [comment]
> 
> 
> skeletal mystic 7604-7605-7606
> I believe tightrope monsters have this issue too, I'll get their ids soon enough

Do you know their hp values?

**Comment by xperiaclash** [comment]
not sure if they scale to team size or not tbh

**Comment by p00boy** [comment]
Yeah, part of the issue I think lies within the scaling of the raid resulting in varied scaling of the monsters hp which is why the hp bars don't give a value, reverting the hp bars for the impacted ones could be changed to be represented with % values rather than absolute values for the sake of simplicity (or reverting all of them back to %)

Regardless here's some info that was requested:
(The following info applies to solo scaled raids (level 123))

Tightrope Deathly Mage 
ID: 7560
Hitpoints: 117

Tightrope Deathly Ranger
ID: 7559
Hitpoints: 117

Skeletal Mystics
ID: 7604 7605 7606
Hitpoints: 156

Shamans
ID: 7573 7574
Hitpoints: 185

**Comment by Ganom** [comment]
Partially fixed in https://github.com/runelite-extended/runelite/pull/628

This will be inaccurate for CM.
