### ISSUE TITLE
Left click trade

### ISSUE THREAD

**Issue by uzot** [runelite-extended/runelite#592]
Instead of always choosing "walk here" on another player make it able to also do "trade" instead of walk here.

**Comment by Kyleeld** [comment]
Best option for this would be to utilise menu entry swapper and hide all except trade. Other than that, this isn’t something we will offer

**Comment by lulwut** [comment]
This would genuinely be a very handy feature for runecraft runners (the trade as left click option). I know I would use it and probably most of the RC running community would do so as well.

**Comment by Ganom** [comment]
I think its worth looking into.

**Comment by se7enAte9** [comment]
This can be accomplished through custom swaps in MenuEntryManager.

**Comment by Kyleeld** [comment]
as above, can be achieved via custom swaps
