### ISSUE TITLE
Zulrah Plugin Sound Loop

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [runelite-extended/runelite#610]
The Zulrah Plugin has a permanent sound loop telling you which prayer to use.

**Comment by Ganom** [comment]
Permanent loop, as in no matter what prayer, it will always loop?

**Comment by ILLuMiNaTe7** [comment]
@Ganom Correct even if you pick the correct prayer it will continue to announce what prayer to use. It even overlaps itself every ~300 ms.

**Comment by f0rmatme** [comment]
Disabling sounds then no sounds will play or loop right? If so don't use the sound config.
Sounds like it needs to be fixed.

**Comment by ILLuMiNaTe7** [comment]
@f0rmatme Correct. No Sound will stop the sound loop from increasing. But the remaining sounds will finish.

**Comment by f0rmatme** [comment]
Fixed
