### ISSUE TITLE
Slayer highlighting True Location inaccurate for monsters larger than 1x1

### ISSUE THREAD

**Issue by farhan1666** [runelite-extended/runelite#612]
[Example at Kurasks](https://i.imgur.com/N1AP3Ry.png) I haven't tested all monsters but if I recall correctly it is off by half a tile for 2x2 monsters and is accurate for 1x1 monsters but serves no real purpose as sw tile is the same thing.

**Comment by farhan1666** [comment]
Also on a separate note having this option in NPC indicators would be nice too, providing it works as intended

**Comment by farhan1666** [comment]
[Example at 2x2 Baby black dragons](https://i.imgur.com/e1XcB6s.png) half a tile off

**Comment by Owain94** [comment]
@Ganom you fixed this in https://github.com/runelite-extended/runelite/commit/4db6403e65f0aec419abb88f21c6e0e906ca0d8f right?

**Comment by xKylee** [comment]
can you confirm if this is still an issue in 2.1.4.0?

**Comment by Owain94** [comment]
Fixed by @Ganom
