### ISSUE TITLE
Gpu plugin removes attack option on skotizo altars

### ISSUE THREAD

**Issue by Lucwousin** [runelite-extended/runelite#613]
When fighting skotizo with gpu plugin activated the "attack" option on awakened altars doesn't appear (it doesn't appear on the altars to begin with, but on a npc on the same tile). For some reason, gpu doesn't render the altar npcs making them unclickable

![with gpu](https://user-images.githubusercontent.com/13177466/59529242-ca569080-8ee0-11e9-8b06-c5c89209c567.png)
![without gpu](https://user-images.githubusercontent.com/13177466/59529245-cb87bd80-8ee0-11e9-9f37-d01734c7cf78.png)

**Comment by xperiaclash** [comment]
well this is a pretty massive bug, almost got me killed in skotizo fight
