### ISSUE TITLE
Lizard Shamans plugin not working in Molch Temple

### ISSUE THREAD

**Issue by NotTeeZee** [runelite-extended/runelite#624]
**Describe the bug**
The Lizard Shamans plug-in does not seem to function when attacking the Shamans in the Lizardmen Temple in Molch (Kebos Lowlands).

**To Reproduce**
1. Go to the Lizardmen Temple in Molch
2. Enable the Lizard Shamans Plugin
3. Attack Lizardman shamans
4. Notice that the plugin does not function in this case.

**Expected behavior**
For the plugin to function (show timer on Lizardman spawns) when attacking Lizardman Shamans in the Molch Temple.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.27-SNAPSHOT
 - Launcher version: 1.6.3-SNAPSHOT

**Comment by Ganom** [comment]
Can you grab the ids of the lizardmen and their spawns?

**Comment by NotTeeZee** [comment]
Definately.

Lizardman shaman ID: 8565
Spawn ID: 6768

Animation ID for Lizardman Shaman that "spawns the spawns": 7157

**Comment by Ganom** [comment]
Im curious, are there names still Lizardman shaman?

**Comment by NotTeeZee** [comment]
Yes
![image](https://user-images.githubusercontent.com/9062226/59556376-f39b1d80-8fc1-11e9-8e8b-290c029fb3e4.png)
