### ISSUE TITLE
Beep timer chime

### ISSUE THREAD

**Issue by alhajriali** [runelite-extended/runelite#630]
Adding beep for prayer,ovls,hitpoints,absorption timers instead of system notification. This was really helpful in konduit and i think it would be beneficial. Beeping would require attention instead of windows notification. Thanks

Beep for 5 times to inform a player that a prayer is lower than the threshold or absorption is. Would be really efficient and afkable instead of windows notification

**Comment by f0rmatme** [comment]
I added sounds to the idle plugin for low hp, etc.

**Comment by alhajriali** [comment]
Prayer, absorption as well? Thanks!

**Comment by Kyleeld** [comment]
as @f0rmatme said, this has been added along with a number of other options :)
