### ISSUE TITLE
Swap Puro-Puro Wheat not working

### ISSUE THREAD

**Issue by w355osrs** [runelite-extended/runelite#631]
Swap Puro-Puro Wheat is not working to make the Magical wheat passable via left click. I've tried restarting the client as well as playing with custom swaps. Also have tried remove and enabling the "hide examine" plugin (as well as other plugins) with no success.

**Comment by coolpick** [comment]
Looks like this is broken again.  I don't see the option anymore.  Not sure if it was removed or if it's just broken.
