### ISSUE TITLE
Menu entry swapper: Shop/stores not swapping values for buy options

### ISSUE THREAD

**Issue by Dark-Xiphles** [runelite-extended/runelite#635]
Menu entry swapper, shop/stores subsection doesn't swap value for buy option.

Config: 
![image](https://user-images.githubusercontent.com/29256122/59567527-36ff9580-906f-11e9-9dfe-96f956cd5a41.png)

Result: 
![image](https://user-images.githubusercontent.com/29256122/59567532-4252c100-906f-11e9-831c-adf28659f1d0.png)

Expected: (Done with custom swap)

![image](https://user-images.githubusercontent.com/29256122/59567522-29e2a680-906f-11e9-9732-e46fd3a4d6ac.png)

**Comment by gazivodag** [comment]
#639
