### ISSUE TITLE
Allied players still attackable in left-click menu after being patched.

### ISSUE THREAD

**Issue by Yeet2018** [runelite-extended/runelite#640]
Clan man mode 'hide attack option for clan members' enabled while in a CC.

Client version: Latest public release.

"Fixed" on: https://github.com/runelite-extended/runelite/pull/505 - The example screenshot is right-click but same issue occurs randomly while hovering over allied player tile. 

![2019-06-16_21-49-35](https://user-images.githubusercontent.com/44622559/59645563-88c42080-9140-11e9-892f-00ed5b8d3416.png)

**Comment by Kyleeld** [comment]
Can you try pvp tools?
