### ISSUE TITLE
Coffer overlay in blast furnace

### ISSUE THREAD

**Issue by Guacrs** [runelite-extended/runelite#641]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Blast furnace usually has an overlay of how much GP is in the coffer. It does not, and has not for a while with rl+

**To Reproduce**
1. Go to Blast Furnace

**Expected behavior**
There is supposed to be an overlay of the coffer, but it's not there.

**Comment by f0rmatme** [comment]
https://github.com/runelite-extended/runelite/pull/463

this change could of broke it maybe, not sure.

we will look into it

**Comment by Guacrs** [comment]
I think you're right, i'll take a look.

**Comment by f0rmatme** [comment]
fixed
