### ISSUE TITLE
Shift to Walk conflicts with Press Enter to Chat

### ISSUE THREAD

**Issue by thebluefish** [runelite-extended/runelite#646]
**Describe the bug**
The plugin `Shift to Walk` does not work while the plugin `Press Enter to Chat` is enabled.

**To Reproduce**
Enable `Shift to Walk`.  
Observe that you can Shift walk through NPCs. 
Enable `Press enter to Chat`.  
Observe that you can no longer Shift walk through NPCs.

**Expected behavior**
Should still be able to Shift walk through NPCs.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.3

**Comment by pklite** [comment]
It also seems like it randomly doesn't work for NPC's even when enter to chat plugin isnt enabled
