### ISSUE TITLE
Remove custom construction menu swap, implement construction plugin which swaps all meta methods.

### ISSUE THREAD

**Issue by lulwut** [runelite-extended/runelite#653]
So, people tend to have a lot of issues with how to work the custom construction plugin - being unsure what to put in. The suggestion is that since people really only do on-meta methods/some specific early level methods to just automatically swap them. Happy to do the work on the plugin/change in code if people think it's a good idea.

**Comment by se7enAte9** [comment]
I don't agree that it should be a separate plugin. The point was to consolidate menu changes by moving most of them to the Menu Entry Swapper plugin. I think a drop down box with meta training methods or separate boxes for common swaps under a construction grouping would make more sense than adding a plugin just for construction menu changes.

**Comment by lulwut** [comment]
Yep that's fair, I agree with that. Just having it as a toggle button instead then?

**Comment by se7enAte9** [comment]
Yes or making a mode for each one and using a drop down box may look better.

**Comment by Ganom** [comment]
Drop box would probably be best if we choose to go this route.

**Comment by Kyleeld** [comment]
with the new easy construction, there is no need to have presets, its extremely easy to use.
