### ISSUE TITLE
RuneLite uses launched monitor resolution for determining resolution to expand to when "maximizing"

### ISSUE THREAD

**Issue by pullup** [runelite-extended/runelite#654]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by f0rmatme** [comment]
what is ...?

**Comment by Ganom** [comment]
Resubmit with proper form or just describe your issue.

**Comment by pullup** [comment]
> Resubmit with proper form or just describe your issue.

ah I'm pissed, I typed it all out, must've reset when I closed the bullshit github popup asking if I wanted to try some bullshit, for fucks sake.

**Comment by pullup** [comment]
> Resubmit with proper form or just describe your issue.

Resubmitted, github being a real cunt with that shit, wtf, clicked the button that way grey as basically "go away" and it did a quasi refresh, which apparently reset my beautiful report.

This one has a bit less effort, but still should get the point across: https://github.com/runelite-extended/runelite/issues/655
