### ISSUE TITLE
RuneLite uses launched monitor resolution for determining resolution to expand to when "maximizing"

### ISSUE THREAD

**Issue by pullup** [runelite-extended/runelite#655]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If you launch the client on a monitor that has a resolution of 800x600 (primary monitor) then drag it over to a monitor that is 1920x1080, when you attempt to maximize it, it will only expand to 800x600.

**To Reproduce**
1. Make your default monitor 800x600 or a lower res than monitor 2
2. Launch RuneLite
3. Drag RuneLite to the secondary (non-primary) monitor that is a greater resolution.
4. Click the "maximize" button
5. Unexpected behavior is the client will fail to properly maximize, and instead use the primary monitor's / launch monitor's max resolution to resize.

**Expected behavior**
When "maximize" is clicked the client should full screen to the new monitor's resolution.

**Screenshots**
![k1fwe3KW2x](https://user-images.githubusercontent.com/21213041/59735546-044ace00-9224-11e9-9c83-4e40b608b41f.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64 Bit, Version 1803
 - RuneLite version: [e.g 1.5.27 SNAPSHOT]
 - Launcher version: [e.g 1.6.3 SNAPSHOT]

**Additional context**
n/a

**Comment by Kyleeld** [comment]
does this behave the same on normal runelite?

**Comment by edgar1016** [comment]
I have had the same issue when building normal Runelite. I found a fix for this was running the jar or building the client using java 8 fixed it for me using any newer version of java always breaks maximizing for me.

**Comment by Kyleeld** [comment]
you have to build with jdk8, any other versions and you will have issues.

**Comment by edgar1016** [comment]
> you have to build with jdk8, any other versions and you will have issues.

I'm aware but when you run the JAR and PATH or JAVA_HOME is set to a higher version it breaks maximizing.

**Comment by pullup** [comment]
> does this behave the same on normal runelite?

Yes

**Comment by pullup** [comment]
> you have to build with jdk8, any other versions and you will have issues.



> > you have to build with jdk8, any other versions and you will have issues.
> 
> I'm aware but when you run the JAR and PATH or JAVA_HOME is set to a higher version it breaks maximizing.

When I do java - version in cmd it returns:
`java version "1.8.0_211"`
I believe that's the correct version, but when I attempt to make sure it starts with that and navigate to my jdk installation then choose "java.exe" in /bin, I see something open for a half a second then instantly close...

**Comment by edgar1016** [comment]
Try making a batch file put it in the same location as your JAR and run it, see if it fixes it.

`@echo off
set path=C:\Program Files\Java\jre1.8.0_211\bin\;%path%
java -version
javaw -jar RuneLitePlus-Launcher.jar
exit`

**Comment by pullup** [comment]
> Try making a batch file put it in the same location as your JAR and run it, see if it fixes it.
> 
> ```
> @echo off
> set path=C:\Program Files\Java\jre1.8.0_211\bin\;%path%
> java -version
> javaw -jar RuneLitePlus-Launcher.jar
> exit
> ```

Just nuked every single java installation, restarted PC, downloaded java 8, ran it, still same issue.

**Comment by pullup** [comment]
> Try making a batch file put it in the same location as your JAR and run it, see if it fixes it.
> 
> ```
> @echo off
> set path=C:\Program Files\Java\jre1.8.0_211\bin\;%path%
> java -version
> javaw -jar RuneLitePlus-Launcher.jar
> exit
> ```

Tried it just for fun anyways (only a slight modification to the jar name was needed) same issue still persists.

**Comment by Kyleeld** [comment]
issue with normal RL, closing issue.
