### ISSUE TITLE
Run pattern helper for Commander Zilyana

### ISSUE THREAD

**Issue by plutori** [runelite-extended/runelite#659]
Commander Zilyana has a very difficult kiting run/shoot pattern I'm having difficulty learning.

The solution I would like is for the client to be able to highlight which actions I should be taking. Something like, highlight the square to run here, then highlight Zilyana when you should be clicking Zilyana to attack them, then highlight square to next run location. Should also take into account whether or not the player has increased range between rune cbow or armadyl cbow.

Can't think of any alternatives, sorry.

Not sure if it would be improper to post a guide to what I'm referring to, but here's what I mean exactly, watch this guide at about 7:30 - https://www.youtube.com/watch?v=e5GPzl599E0

Guy in the guide makes it look easy obviously, since he's an experienced Zilyana runner, but, it ain't so easy after going there to try it and dying horribly a few times already.

**Comment by Ganom** [comment]
I don't see this as a needed plugin, but I might revisit in the future.
