### ISSUE TITLE
Kept on death does not work at all

### ISSUE THREAD

**Issue by HOOD-APPARITION** [runelite-extended/runelite#665]
Kept on death does not work at all. 

![image](https://user-images.githubusercontent.com/50153768/59817831-0cb80d00-92e7-11e9-8f25-3113ac0668f2.png)

**Comment by Ganom** [comment]
This was disabled when our old client patching system was broken, i'll look and see if we can re-enable it.

**Comment by Lucwousin** [comment]
Not needed anymore cause of runelite update
