### ISSUE TITLE
Supply tracker tends to add random items

### ISSUE THREAD

**Issue by HOOD-APPARITION** [runelite-extended/runelite#666]
The supply tracker tends to add random items to the food consumed list. It'll randomly say I consumed a dragon plateskirt or an AGS and add the value of the object to the overall supplies used. 

I think it has something to do with the price checker because I price checked an AGS and a while later, it popped up in my supply tracker.

**Comment by Dyldozer** [comment]
Tends to happen when an object is moved into the slot of a consumable when consumed. There is a few ways I thought about rewriting it to fix but all would require a decent amount of logic and might bloat it like crazy

**Comment by stantor42** [comment]
[Same](https://i.gyazo.com/6a998bd5a41cf2e85d2bf963fc4da186.png)

**Comment by f0rmatme** [comment]
https://github.com/runelite-extended/runelite/issues/666#issuecomment-503878571

wont be fixed unless someone else rewrites this plugin
