### ISSUE TITLE
request: tob purple tornado marker

### ISSUE THREAD

**Issue by schokkya** [runelite-extended/runelite#678]
Could you possibly add a marker of your own purple tornado following you? 
You could record a few game ticks and check if on those ticks the tornado has been on the same tiles as you were and mark it.

**Comment by SRLJustin** [comment]
could you turn on 'Interacting' in the Dev Tools plugin and see if you can see a blue line attached to your player and the tornado?

**Comment by schokkya** [comment]
> could you turn on 'Interacting' in the Dev Tools plugin and see if you can see a blue line attached to your player and the tornado?

Unfortunately I am unable to do tob for the time being, but I do know for a fact that the tornado does not interact with players(phoneman and lyzrds told me this a while back).

**Comment by Ganom** [comment]
Not sure if this is possible, but we'll take a look eventually. Don't expect anything soon.

**Comment by farhan1666** [comment]
Can confirm nado does not interact with you

**Comment by farhan1666** [comment]
Also worth noting that a useful variation of this would be making it so that you can only see your tornado

**Comment by farhan1666** [comment]
The tornado does not follow you traditionally, it checks every tick where you are, and moves a tile North south east or west that will bring it closest to your position on that tick, if this direction could be determined by the client then after a few ticks you could identify which tornado follows which player

**Comment by Kyleeld** [comment]
as this doesnt "interact"/follow your player and just moves in the general direction, i don't believe this will be something we implement.
