### ISSUE TITLE
Add the player's game mode icon on player menus.

### ISSUE THREAD

**Issue by Cameronza** [runelite-extended/runelite#699]
The ability to see a player's game mode icon upon right clicking the player. This would be useful so you would know who's an Ironman without searching them on the highscores.

**Comment by tomcylke** [comment]
Seems kind of unnecessary, they'll tell you anyways if you wait 30 seconds. :^)

**Comment by Lucwousin** [comment]
Don't think there's a way to know someone else's status unless they talk (or if you look them up on the highscores but eh)

**Comment by Cameronza** [comment]
> Seems kind of unnecessary, they'll tell you anyways if you wait 30 seconds. :^)

It would mainly be helpful for any competition killing monsters, especially for Slayer. This would be easier than looking them up and switching to Ironman highscores.

**Comment by Lucwousin** [comment]
Tell me how then

**Comment by tomcylke** [comment]
I'm not a fan of ironman mode either, but adding a plugin just so people can crash them more easily kinda seems like a dick move. Just saying. 
Related https://gyazo.com/068e4348ee5ac75077ca9b59b94259ee

**Comment by Ganom** [comment]
This would require a non-insignificant amount of api calls.
