### ISSUE TITLE
Loot tracker monster filter

### ISSUE THREAD

**Issue by Crystalknoct** [runelite-extended/runelite#702]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Its always a pain when doing chambers of xeric and your "Loot Tracker" gets flooded with scav drops, and boss potion drops. Would be nice if it could be filtered somehow.
**Describe the solution you'd like**
Maybe add a customization monster filter so certain things are ignored completely?
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
If not customizable maybe just have a trigger for cox monsters aside from the loot from chest and maybe onyx?
**Additional context**
Don't have anything to reference at the moment.
https://i.imgur.com/rLPjyox.png

**Comment by Crystalknoct** [comment]
Added image as example as it is

**Comment by f0rmatme** [comment]
Added
