### ISSUE TITLE
Left Click "Build Storage Unit" for CoX

### ISSUE THREAD

**Issue by sunha7** [runelite-extended/runelite#704]
Left click "Build" for the unbuilt chest (Storage Unit) in Chambers Of Xeric. Useful for the lazy who believe having to right click then build is not the right way!

I'd guess this would be integrated in Menu Entry Swapper but could also go in CoX Helper?

image of menu: https://i.imgur.com/uooIVPq.png

**Comment by Lucwousin** [comment]
I feel like custom swaps are fine for this
