### ISSUE TITLE
cox scouter not showing recommended items

### ISSUE THREAD

**Issue by xperiaclash** [runelite-extended/runelite#713]
**Describe the bug**
cox scouter overlay is  not showing recommended items for the raid presented

1-enter raids

**Expected behavior**
overlay should contain recommended items for each room

**Screenshots**
https://gyazo.com/6f690631d874eb88a72da3f3a3d7aee6

**Environment (please complete the following information):**
 - OS: windows
 - RuneLite version: latest
 - Launcher version: latest

**Comment by Ganom** [comment]
![image](https://user-images.githubusercontent.com/8338284/59981547-f0f88380-95d2-11e9-98bf-b7907f487cf9.png)
Working on live client.
