### ISSUE TITLE
Make inventory grid squares appear when items are clicked on.

### ISSUE THREAD

**Issue by rsnoob93** [runelite-extended/runelite#718]
Would it be possible to make a plugin that makes it easier to see when an item has been clicked on, like for gear swapping? The default vanilla dimming is hard for me to see. I used to be able to use anti-drag + inventory grid tiles to see if I clicked properly, but that interaction disappeared when inventory grid was added to mainline RL. I'd personally like to see an option for the entire inventory grid to pop up whenever an item is left click pressed, but even just having translucent squares overlaid on individual items as they're clicked would be nice.

**Comment by Kyleeld** [comment]
inventory grids is something that only triggers when being dragged, it is 100ms before it appears when dragging, which when coupled with antidrag should be fine.

as for clicking it and the invent grid popping up, this isnt something we would implement.
