### ISSUE TITLE
Add Abyssal Tentacle and Vengeance to raid scouter

### ISSUE THREAD

**Issue by Crystalknoct** [runelite-extended/runelite#724]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
No big deal just would be nice to help explain to learners what to bring for what raid.
**Describe the solution you'd like**
Have Icons for the Weapon/Spell
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Combine them with alternatives IE ZGS/Ice Barrage/Abyssal Tentacle can be used on Mutta
Vengeance and Dsword/Abyssal dagger can be used on Vasa crystal among other things
**Additional context**
Just that if implemented I can imagine it would take up a bit of space in some instances maybe having items relevant together would be beneficial to the layout.

**Comment by Kyleeld** [comment]
this isn't something we will do. if you don't have the required items, i'm sure the teammates can confirm alternatives.
