### ISSUE TITLE
Combine all RL+ Boss Helper Plugins into one.

### ISSUE THREAD

**Issue by lulwut** [runelite-extended/runelite#741]
To reduce plugin config bloat (too many things in the list of plugins) I suggest that all PvM helpers be merged into one. This would provide a central hub where all of the boss/enemy plugins can be managed/seen and remove all of the single entry plugins from the config list.

**The current ones which I am suggesting to be merged are:**

> - Zulrah Helper
> - Vorkath Helper
> - Vetion Helper
> - Lizard Shamans (Could be left out as it's not a boss per se) 
> - Hydra Helper
> - Grotesque Guardians
> - Alchemical Hydra

I **do not** think instanced/complicated bosses should be merged (TOB/COX/Fight Caves/Inferno).

**Comment by Kyleeld** [comment]
This is not something we wish to do at this time
