### ISSUE TITLE
Whale Watchers: Protect item doesn't work in pvp-worlds. Only works in the wilderness.

### ISSUE THREAD

**Issue by veteranosrsplayer** [runelite-extended/runelite#750]
**Describe the bug**
The huge red filter doesn't pop-up when skulled in a pvp-world. It only does in the wilderness.

**To Reproduce**
1. Make it so that when you are skulled in a pvp-world, the filter does pop-up when you don't have protect item enabled.

Windows 10 64-bit pc with latest java installed, fresh install.

**Comment by veteranosrsplayer** [comment]
Tried to come up with solutions with Dev. Kyle, but to no avail. 

Tested on these worlds, on two computers:
325;
371;

Being skulled while in a pvp-area on the pvp-worlds, does not enable the filter from whale watchers. 
Being skulled while in a bountyhunter-world entering the wildy, or being in a normal pk world entering the wildy, the plug-in works correctly.

**Comment by veteranosrsplayer** [comment]
![Untitled](https://user-images.githubusercontent.com/52208909/60126725-e97dd980-978e-11e9-9d75-52a290dfb067.png)

**Comment by pklite** [comment]
good catch, fixing this now
