### ISSUE TITLE
Items kept on death plug-in doesn't work for me, even with the normal runelite setting.

### ISSUE THREAD

**Issue by veteranosrsplayer** [runelite-extended/runelite#751]
Having the normal Runelite plug-in enabled, it still doesn't work for me. Maybe there's a code interfering?

It could be a client-sided issue, not sure what's wrong here.

**Comment by f0rmatme** [comment]
did resetting the client also fix this?

**Comment by veteranosrsplayer** [comment]
Resetting and clean installing everything did not fix the issue. I will reproduce what I tried:

- Tried enabling both inventory items kept on death plug-ins, the one from RL+ and the one from the standard RL. It didn't work.
- Tried enabling only the original RL plug-in, and it didn't work aswell. 

I've read on Discord saying that it's a known issue, but it shouldn't happen with the original RL's plug-in as the RL+ one is only an enhancement of the original plug-in if I'm correct.
