### ISSUE TITLE
Incorporate Henke's line of sight spreadsheet into Inferno plugin

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite-extended/runelite#754]
https://henke96.github.io/Lineofsight/

Heard about this from Adwaam which he found through Xzact

**Comment by Kyleeld** [comment]
not something we will add.

**Comment by Lucwousin** [comment]
Reopening cause its interesting and may or may not be of use

**Comment by ReeeMan** [comment]
> Stale issue message

Yikes big stale.

Anyway someone can close this.
Lohouse is working on this with his Inferno rework
