### ISSUE TITLE
highlightable objects

### ISSUE THREAD

**Issue by dipkip9** [runelite-extended/runelite#787]
![highlight specific objects](https://user-images.githubusercontent.com/52148915/60320353-b21f5080-9979-11e9-8efb-66cc540fd99d.png)

I would like to be able to highlight specific objects within the game, in the picture I use the Game Objects feature to highlight the Young tree's. The problem with doing this is that it highlights every object which makes the game lag quite a bit.

in this picture I'm using the Game Objects feature to give an example of what it could look like. Or maybe it could be an idea to use the object number to highlight specific objects or use the object name just like the "Custom Swaps" feature.

I am however not knowledgeable about coding so I'm just trying to give some suggestions which might be of some help to you.

Thank you for your time and for the amazing client and keep up the amazing work :).

**Comment by ocekyled** [comment]
You should be able to do this with the current "Object Markers" plugin, by holding shift and right clicking the object, much the same as when you mark tiles. 
Ex: ![9UTW9cuwLY](https://user-images.githubusercontent.com/19616058/60324069-e703c580-99c2-11e9-95a3-9093de78bfcf.gif)

However, it does appear that this functionality is broken in the current build of runeliteplus, with the options for marking objects and tagging npcs not showing in the right click menu.
Ex: ![mm3rCh1G0O](https://user-images.githubusercontent.com/19616058/60324137-1b778180-99c3-11e9-96a6-8a77f417fc8c.gif)

**Comment by Kyleeld** [comment]
Known issue fixed next update

**Comment by dipkip9** [comment]
AH! thanks for telling me about objects markers, I hadn't seen that plugin.
Sorry for requesting an already existing plugin!

**Comment by ocekyled** [comment]
> Known issue fixed next update

This is still occurring with both NPC Indicators and Object Markers
