### ISSUE TITLE
Reintroduce the future to enable anti-drag 24/7 when opening the client without having to push the button, have it disabled on default 

### ISSUE THREAD

**Issue by veteranosrsplayer** [runelite-extended/runelite#792]
Reintroduce a toggle to make it possible for anti-drag to be enabled 24/7, even when relaunching the client. 

Make it disabled on default for users who don't want to, and keep the keybind to make both parties happy.

Referral ST0NEWALL: 

![Untitled](https://user-images.githubusercontent.com/52208909/60345186-b7e85680-99b8-11e9-94d7-51928630683d.png)
![Untitled2](https://user-images.githubusercontent.com/52208909/60345187-b7e85680-99b8-11e9-9a9e-3b23c43b7588.png)

**Comment by Ganom** [comment]
Isn't it already a toggle? I know it resets on focus loss if you have that enabled.

**Comment by veteranosrsplayer** [comment]
What I've been told by kyle, is that the option 'keybind'; when you push your key it will enable it for the time being, but I think it would be a QoL if there would be a button to turn it on 24/7. 

Personally I think it's annoying if you reset the client you have to turn it on again by pushing a button, why not just make it so when you click an option to enable it forever. This can be disabled on default for users that don't want that. 

My first interpretation was that you had to hold the button down in order to enable it, pking like that would've been lame. I also think it's a bit unclear tho, I bet most people think when they click on the slider to enable anti-drag, it's enabled by default, but it isn't.

**Comment by Ganom** [comment]
I mean, toggle is what it says, a toggle. But we can add a config option that will make it persist until turned off.

**Comment by veteranosrsplayer** [comment]
In my honest opinion, that would be awesome. I don't want to sound rude or persistent but it has been bothering me for a while. I appreciate the team's work and thanks for taking it into account.
