### ISSUE TITLE
Fight caves Prayer text not showing properly

### ISSUE THREAD

**Issue by flewychan** [runelite-extended/runelite#807]
**Describe the bug**
Fight caves prayer text not properly shown on rangers/magers if there are more than 1

**To Reproduce**
1. Turn on Fight caves plugin and wait till you encounter 2x range/magers

**Expected behavior**
Prayer text timers should be shown on each individual monster

**Environment (please complete the following information):**
 - OS: Windows
- Runelite Version: 1.5.28

PS. Also not sure if it was removed but there used to be highlights for drainers (to notice them easier) but latest version does not have them

**Comment by Kyleeld** [comment]
just tested, this is working fine

**Comment by Kyleeld** [comment]
also, drainer hightlighting was removed.

**Comment by Ganom** [comment]
> 
> 
> **Describe the bug**
> Fight caves prayer text not properly shown on rangers/magers if there are more than 1
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Turn on Fight caves plugin and wait till you encounter 2x range/magers
> 
> 
> **Expected behavior**
> Prayer text timers should be shown on each individual monster
> 
> **Environment (please complete the following information):**
> 
>     * OS: Windows
> 
>     * Runelite Version: 1.5.28
> 
> 
> PS. Also not sure if it was removed but there used to be highlights for drainers (to notice them easier) but latest version does not have them

Just so it is known, It does show properly, but it might be a bit odd, because its only showing the lowest tick timer, so if one npc has 2 ticks left, and one npc has 1 tick left, when the next tick happens, it will stay at 1 tick in the prayer interface for those 2 ticks.

**Comment by flewychan** [comment]
I see, thank you so much for the replies lads!
