### ISSUE TITLE
Cannon common spots not showing 

### ISSUE THREAD

**Issue by flewychan** [runelite-extended/runelite#808]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Turning on Cannon common spots doesnt show common spots

**To Reproduce**
Turn on 'Show cannon common spots' under Cannon

**Expected behavior**
Cannon common spots should be shown on to the game

**Additional context**
Turning on/off double hit spots will show the 'common cannon spots' but without turning on 'double hit spots' it wont show at all

**Comment by ThatGamerBlue** [comment]
do you have a cannon in your inventory?

**Comment by flewychan** [comment]
yes i certainly do have a cannon in my inventory.

**Comment by SRLJustin** [comment]
Can you do me a favor and when you're at the cannon spot, if you have a slayer helm or gem, can you please right-click it and click 'Check' so it will show what task you have in your chatbox, then let me know if the cannon spot shows, if not, toggle the plugin and let me know if that enables the spot

**Comment by Ganom** [comment]
Should be fixed in https://github.com/runelite-extended/runelite/pull/810
