### ISSUE TITLE
opening worldmap - makes you switch to 1 mouse button option! (always right click)

### ISSUE THREAD

**Issue by kleinen666** [runelite-extended/runelite#809]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by SRLJustin** [comment]
Unable to replicate this issue, can you make a quick video/gif of this issue?

**Comment by kleinen666** [comment]
im not home atm

Verstuurd vanaf mijn iPhone

Op 29 jun. 2019 om 14:23 heeft Justin <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Unable to replicate this issue, can you make a quick video/gif of this issue?

**Comment by sdburns1998** [comment]
Het probleem dat er voor zorgde dat je alleen nog je rechtermuisknop kon gebruiken is opgelost in de laatste update, als je gebruikt maakt van de launcher hoef je niet te updaten dat gebeur namelijk automatisch. Als je gebruikt maakt van het jar bestand moet je de nieuwe update downloaden.

**Comment by kleinen666** [comment]
mijn excuses, dacht dat et aan myn instellingen zou gelegen hebben

Verstuurd vanaf mijn iPhone

Op 29 jun. 2019 om 20:36 heeft sdburns1998 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Het probleem dat er voor zorgde dat je alleen nog je rechtermuisknop kon gebruiken is opgelost in de laatste update, als je gebruikt maakt van de launcher hoef je niet te updaten dat gebeur namelijk automatisch. Als je gebruikt maakt van het jar bestand moet je de nieuwe update downloaden.

**Comment by ThatGamerBlue** [comment]
Is this resolved in the latest version?

**Comment by Lucwousin** [comment]
That's what owain said in his comment at least
