### ISSUE TITLE
API Calls cause RuneLite Extended to micro-stutter

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#812]
When using the !price command (or any other API call on RuneLite+) the client will have a micro-stutter while the API call is executing. this isn't an issue on Vanilla RuneLite. 

This is the vanilla RuneLite client API call: https://i.imgur.com/5BK1M6S.gifv

This is RuneLite+ client API call: https://i.imgur.com/gKayuSz.gifv

This might not look like an issue but in a high populated area where people are using !price, !kc, !lvl etc this can be very annoying

**Comment by Ganom** [comment]
I'm going to assume this is a thread related issue.

**Comment by SRLJustin** [comment]
if this issue isn't going to be fixed can we revert the api calls back to the official runelite api so we dont have this issue?
