### ISSUE TITLE
Swapper working to slow

### ISSUE THREAD

**Issue by Dark-Xiphles** [runelite-extended/runelite#819]
The reworked swapper is making the swaps too slow. I assume this has to do with the reduction of swaps to one swap per gametick, and clicking for before the next swap happens.

**To Reproduce**
1. Pick a certain swap (noticed it mostly on essence pouches, so I'm using those)
2. Open bank and quickly click the pouches to fill them.
3. Pouches won't be filled, and if they get filled, they won't take the first essence as they normally do.

Videos:
Original video, with lavas in RCing enabled:
https://drive.google.com/file/d/1LmEhjkISx3g7x12wH_yYyB0mqx8Twu_u/view 
Kyle suggested turning lavas off, still same effect:
https://drive.google.com/open?id=1v9722BGxlYVU0QfIL7e8u_sGCLR_LgPn

**Comment by Kyleeld** [comment]
cannot replicate, can you see if this still happens?

**Comment by Dark-Xiphles** [comment]
Yep still having this problem, haven't noticed it on anything else than the essence pouches, but haven't tested it thoroughly.

**Comment by farhan1666** [comment]
This issue is also appears when using MES to left click drop items when powerskilling
