### ISSUE TITLE
Construction left click to build

### ISSUE THREAD

**Issue by Crystalknoct** [runelite-extended/runelite#821]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Trying to use 1 click construction the script doesnt swap the initial build option but still swaps the removal of it fine. Was testing for a friend and couldnt reproduce working expectations. 
**To Reproduce**
1. Go to '1 click constructiuon plugin try to build Gnome Benches'
2. Click on 'The build location for benches it wont swap to left click build but instead stays as walk here'
3. Scroll down to 'No where?'
None could be found he uses EXE
**Expected behavior**
I expected the one click construction plugin to one click left click on the Bench area to build and remove flawlessly currently only removal works properly.
**Screenshots**
None would help really.
**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10
 - RuneLite version: [e.g 1.4.6] 1.5.28-SNAPSHOT
 - Launcher version: [e.g 1.5.2] 1.63-SNAPSHOT

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

Checked his logs no information regarding the plugin.
[SPOILER_application.log](https://github.com/runelite-extended/runelite/files/3342253/SPOILER_application.log)
[SPOILER_launcher.log](https://github.com/runelite-extended/runelite/files/3342254/SPOILER_launcher.log)
[SPOILER_client.log](https://github.com/runelite-extended/runelite/files/3342255/SPOILER_client.log)

**Comment by se7enAte9** [comment]
They have different names, so your list needs to consist of both the name prior to building and what it is after. In this case that would be `seating space, gnome bench`
