### ISSUE TITLE
Object Marker

### ISSUE THREAD

**Issue by shaun71190** [runelite-extended/runelite#825]
Object marker is not working. When shift+right click object marker option doesnt appear even if you have the option turned on

**Comment by PaulVlahosCS** [comment]
I am having this issue as well. To troubleshoot this I turned off any plugin that has to do with working off a keybind press. I also tried turning off any plugin that changes menu entries at all (except object marker).

**Comment by foz420** [comment]
Having the same issues, object/npc indicators don't work ever since shift-walk was implemented

**Comment by Kyleeld** [comment]
caused by shift to walk using addPriorityEntry.

addPriorityEntry Adds to the set of menu entries which when present, and then will remove all entries except for the one utilising addPriorityEntry, in this case, WALK HERE or TAKE.

**Comment by PaulVlahosCS** [comment]
I don't have the shift to walk here plugin on though.

**Comment by Kyleeld** [comment]
Enable and disable it. The only time this happens is if you have shift to walk on, if you have enable it conflicts

**Comment by foz420** [comment]
I don't have it enabled either and i've tried turning it on and off again, makes no difference. also tried turning on and off other plugins I thought may be conflicting but nothing works

**Comment by PaulVlahosCS** [comment]
First off I've never used the shift walk here plugin. Secondly I enabled and disabled every single plugin and object marker doesn't want to work. NPC indicators is fine. When I get home from work I'll try to troubleshoot it since it has to be the object marker plugin itself at this point.

**Comment by Ganom** [comment]
This is not something you guys can fix, it was related to a change made by accident to the menu-entry-added event where the type and identifier got swapped. It will be swapped back.
