### ISSUE TITLE
Olm cripple timer

### ISSUE THREAD

**Issue by Crystalknoct** [runelite-extended/runelite#829]
**Describe the bug**
During raids if olms melee hand is crippled it no longer has a timer for its duration
**To Reproduce**
1. Go to 'Chambers of Xeric olm'
2. Click on 'Melee hand till it cripples'
3. Scroll down to 'The bottom of this post'
I dont have logs of such errors regarding it.
**Expected behavior**
The hand to be outlined like it did a few patches prior and then display the time of cripple. Nothing major though.
**Screenshots**
None currently if I raid later I will.
**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10
 - RuneLite version: [e.g 1.4.6] 1.5.28-SNAPSHOT
 - Launcher version: [e.g 1.5.2] Unknown(Build)

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[application.log](https://github.com/runelite-extended/runelite/files/3342662/application.log)
[client.log](https://github.com/runelite-extended/runelite/files/3342663/client.log)
[launcher.log](https://github.com/runelite-extended/runelite/files/3342664/launcher.log)

**Comment by xperiaclash** [comment]
pretty sure this was working for more than 20 raids, gonna test it out again and let you know

**Comment by xperiaclash** [comment]
https://gyazo.com/dd4532e48e15dda54a9847ad7b69c979
working per usual

**Comment by lulwut** [comment]
Has been working fine for me as well.

**Comment by Crystalknoct** [comment]
https://i.imgur.com/Rdq9m85.png The timer on olm left hand isnt working when I build the client is there a setting I need to have turned on?

**Comment by xperiaclash** [comment]
only cox helper plugin, make sure you update your project

**Comment by Crystalknoct** [comment]
solved was the issue im just behind on rev ty
