### ISSUE TITLE
Kraken doesn't count for Kraken slay task

### ISSUE THREAD

**Issue by lulwut** [runelite-extended/runelite#830]
Kill kraken, KC left won't go down on the slayer kills left overlay or the helm overlay. Video attached of me manually having to update KC left.

https://streamable.com/779qx

**Comment by lulwut** [comment]
For what it's worth the following has the Kraken ID and animation 
![image](https://user-images.githubusercontent.com/287285/60394322-70a7c480-9b76-11e9-8f12-dd2709d73a4f.png)

**Comment by SRLJustin** [comment]
#557

**Comment by lulwut** [comment]
Ta, apologies
