### ISSUE TITLE
Cerberus plugin only working intermittently

### ISSUE THREAD

**Issue by Icenix** [runelite-extended/runelite#832]
**Describe the bug**
Cerberus plugin seems to only work for a while.
Then it stops showing prayer overlays.
Have been toggling the plugin off and on to get it working again

**To Reproduce**
Kill Cerberus

**Expected behavior**
Work always

**Screenshots**

**Environment (please complete the following information):**
 - Windows 10
 - RL+ - Latest git pull

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue after todays update?

**Comment by Icenix** [comment]
Seems alright now - thanks
