### ISSUE TITLE
NPC/Object Resize [S]

### ISSUE THREAD

**Issue by llerb** [runelite-extended/runelite#845]
**When the client is on max outer zoom...**
So I'm testing out Ourania (ZMI) altar with the client. As its possible with the full outer zoom to one click the ladder, bank and altar without using any arrow keys or zooming in/out. The current way of making this a little easier is highlighting tiles/objects/npc's. Although as its in the outer zoom limit the click box is tiny.

**Resizing specific NPC's/Objects**
Being able to resize the ladder, banker and altar in this scenario would make the grind a lot easier. I also see this being a helpful plugin for other types of grindy skilling. WC'ing would be a lot easier (especially if doing bank trips), as well as fishing and all other collectable skills.

The plugin would be similar to spellbook resize. Another QOL.

![Capture](https://user-images.githubusercontent.com/52413369/60439112-12c4bc80-9c0a-11e9-95d1-36f6559f3c6a.PNG)

**Comment by Owain94** [comment]
I believe that this could lead to bans

**Comment by IanWONeill** [comment]
> I believe that this could lead to bans

I agree, maybe this is one for the External Plugin users.
