### ISSUE TITLE
Barbarian Assault plugin causes Desert goat horn to be non-interactive

### ISSUE THREAD

**Issue by thebluefish** [runelite-extended/runelite#848]
**Describe the bug**
While the `Barbarian Assault` plugin is enabled, unable to interact with `Desert goat horn` in the inventory.

**To Reproduce**
1. With the `Barbarian Assault` plugin disabled, withdraw `Desert goat horn` to inventory.  
2. Observe you can `Use` the `Desert goat horn`.  
3. Enable `Barbarian Assault` plugin.
4. Observe that you can no longer interact with the `Desert goat horn`.

**Expected behavior**
Should be able to use the `Desert goat horn`.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.28
 - Launcher version: 1.6.3

**Comment by Ganom** [comment]
Fixed in https://github.com/runelite-extended/runelite/pull/852
