### ISSUE TITLE
Clan chat bug

### ISSUE THREAD

**Issue by githubuser12323** [runelite-extended/runelite#863]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Not being able to hit clan chat members.

**Additional context**
Turned off/on every single plugin and nothing worked.
Screenshots :
https://gyazo.com/bb92da072463da6a98c7dbe9760b0dc4
https://gyazo.com/b5459f4b0febc508576b8b7790813bf9
https://gyazo.com/8372dbdf555f22e74f40651e5a6d7cda

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue after todays update?

**Comment by Kyleeld** [comment]
fixed in #900
