### ISSUE TITLE
Rightclick menu entry swapper broken

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#865]
using the lasting pull from github, rightclick menu doesnt reflect the menu entry swapper:

https://i.imgur.com/y7ZLBnu.png vs the rightclick menu https://i.imgur.com/km2QXmx.png

plugin options:

https://i.imgur.com/MOQI9Kj.png

**Comment by whocodes** [comment]
Also `Hide Report` and `Hide Examine` quit working

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue after todays update?

**Comment by SRLJustin** [comment]
issue has been fixed after todays update - closing
