### ISSUE TITLE
Tick / X broken in clue overlay

### ISSUE THREAD

**Issue by HSJ-OSRS** [runelite-extended/runelite#869]
**Describe the bug**
The tick/X indicator to show whether you do or don't have the required clue item in your invent or if you have the stash unit built doesn't show correctly

**To Reproduce**
Steps to reproduce the behaviour:
Open a emote clue of any tier

**Expected behaviour**
A tick or an X to be shown

**Screenshots**
Current
![Bug](https://i.imgur.com/hnb1Fmb.png)
Expected
![Expected](https://i.imgur.com/sHKItPK.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: Latest pull

**Comment by f0rmatme** [comment]
tbh i think that looks better, our font update maybe is causing this.

**Comment by Ganom** [comment]
> 
> 
> tbh i think that looks better, our font update maybe is causing this.

Yes, it is. Its missing the unicode characters for these.

**Comment by Kyleeld** [comment]
fixed in latest

**Comment by f0rmatme** [comment]
https://github.com/runelite-extended/runelite/pull/1070
