### ISSUE TITLE
Graphical glitchiness.

### ISSUE THREAD

**Issue by IanWONeill** [runelite-extended/runelite#870]
![](https://godhatesfags.church/8uMV2A9m6FuSUXQ.gif)

As you can see by the gif there are Glitchy tiles across the map, they all seem to be in the same place each time. The color is the same color as the Skybox.

This only started happening recently within the last day or so. I'm not sure what could be causing the issue or if anyone else is having the issue.

It persists when I disable all plugins and my Logs seem clean of errors apart from Item prices and Slayer stuff.

**Comment by f0rmatme** [comment]
https://github.com/runelite-extended/runelite/wiki/Disable-Hardware-Acceleration

try this
