### ISSUE TITLE
Loot Assist Plugin Countdown Goes Into Negatives

### ISSUE THREAD

**Issue by bigmemes420** [runelite-extended/runelite#874]
**Describe the bug**
The loot assist plugin counts down into negatives for a second before items spawn.

**To Reproduce**
1. Turn on the plugin and see a player die
2. Wait for the timer to reach 0

**Expected behavior**
Once it reaches 0 it should be when items spawn/become visible to you

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue after todays update?

**Comment by bigmemes420** [comment]
Yes by about 1 second
