### ISSUE TITLE
Editing shift click options & inventory tags does not work 

### ISSUE THREAD

**Issue by w355osrs** [runelite-extended/runelite#875]
Current shift click options and inventory tags work but you cannot edit them.

**Comment by thebluefish** [comment]
Confirmed. I tried disabling every other plugin, but could not get these options to work.

**Comment by Kyleeld** [comment]
can you confirm if this is still the case after todays updtae?

**Comment by Whatwhatio** [comment]
Issue still there.
I right click inventory icon, configure shift-click, tried changing Grimy Toadflax to use, but it says it's already on it and the shift just drops it

**Comment by w355osrs** [comment]
both still don't work (shift click inventory tag or shift click editing)

**Comment by se7enAte9** [comment]
In work, see #899

**Comment by Kyleeld** [comment]
resolved in #899
