### ISSUE TITLE
Scaling with OS

### ISSUE THREAD

**Issue by jancoz** [runelite-extended/runelite#879]
If you scale in Windows the interface of Runelite Plus doesn't scale with it. I need to scale 200% on my laptop, the interface of Runelite is so small that it's unusable.

**Comment by Kyleeld** [comment]
Can you confirm if this is an issue in runelite too?

**Comment by jancoz** [comment]
It's not an issue in Runelite, only in Runelite Plus

**Comment by sdburns1998** [comment]
Are you using the launcher or the jar?

**Comment by f0rmatme** [comment]
https://github.com/runelite/runelite/wiki/Change-DPI-Scaling-%28Windows%29

**Comment by jancoz** [comment]
> Are you using the launcher or the jar?

The launcher



> https://github.com/runelite/runelite/wiki/Change-DPI-Scaling-%28Windows%29

This is a good temporary solution, but it is not of the same quality as proper slacing, like Runelite or the original OSRS launcher use. Using this method is effectively magnifying resulting in a very blurry OSRS interface.
