### ISSUE TITLE
Black tiles

### ISSUE THREAD

**Issue by Vokuar** [runelite-extended/runelite#880]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
black boxes on highlighted tiles

**To Reproduce**
no idea as i was theiving at the time with line of sight

**Expected behavior**
continued gameplay

**Screenshots**
<a href="https://i.imgur.com/3u9wCC0.png"><img src="https://i.imgur.com/3u9wCC0m.jpg"></a>
**Environment (please complete the following information):**
 - OS: Win 10
 - RuneLite version: [1.5.28-SNAPSHOT]
 - Launcher version: [1.6.3-SNAPSHOT]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by ThatGamerBlue** [comment]
Cannot replicate, do you have gpu mode enabled?

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue after todays update?

**Comment by Lucwousin** [comment]
Looks like your gpu doesn't know how to handle alpha to me, probably not something we're gonna be able to fix

**Comment by f0rmatme** [comment]
Try using the EXE build over jar
