### ISSUE TITLE
MenuManager Crashing

### ISSUE THREAD

**Issue by tomcylke** [runelite-extended/runelite#884]
I'm not sure exactly what causes it, but I've had the game crash with this error multiple times while in inferno. Likely something to do with MenuManager.
![a1c986a03db9ea841fcf0df42c820387](https://user-images.githubusercontent.com/6732254/60688592-32671980-9e84-11e9-80f0-b1b50ee1b2d1.png)

**Comment by se7enAte9** [comment]
Fixed in #866
