### ISSUE TITLE
Wilderness levels and deadman mode safe zone switched

### ISSUE THREAD

**Issue by githubuser12323** [runelite-extended/runelite#892]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If you 'tick' the deadmen mode safezones setting found in the multi-lines, it instead shows you the wilderness level lines.

**To Reproduce**
1. Go to Multi-Lines
2. Click on Deadmen mode safezones

**Expected behavior**
Shows you Deadmen Mode safezones not the wilderness level lines.

**Screenshots**
https://i.gyazo.com/thumb/1200/042e27687d880a179094a66a6cd63ee4-png.jpg
https://i.gyazo.com/thumb/1200/904a79ea5d49bc6d01964be7a34e9cd5-png.jpg

**Comment by Kyleeld** [comment]
fixed in #900
