### ISSUE TITLE
rune pouch bold font still visible

### ISSUE THREAD

**Issue by xperiaclash** [runelite-extended/runelite#893]
**Describe the bug**
bold font still visible on the rune pouch

https://gyazo.com/ad958e28013aaedb9148ff80a31445c0

latest version

**Comment by SRLJustin** [comment]
Also changing the font in the RuneLite plugin will cause the Rune Pouch overlay repeat twice, once with the bold font (in picture) and then with the other font you selected

**Comment by xperiaclash** [comment]
can we revert #851 ? like serious..

**Comment by f0rmatme** [comment]
no, go in your settings and change your font settings for now. will look for a fix

**Comment by f0rmatme** [comment]
fixed
