### ISSUE TITLE
Clue scroll plugin not functioning

### ISSUE THREAD

**Issue by ValleyWest** [runelite-extended/runelite#901]
Clue scroll hints do not appear in current version of Runelite Plus. Clue scroll hints do not appear on the map.

Enabling/Re-enabling the plugin does not remedy the issue.

Jumping over to Runelite, it does not appear to be an issue with the base Runelite client.

**Comment by Vikings09876** [comment]
Having same issue

**Comment by ValleyWest** [comment]
Issue resolved with July 7 update.
