### ISSUE TITLE
Boosts information - Display buff changes not working

### ISSUE THREAD

**Issue by Icenix** [runelite-extended/runelite#905]
**Describe the bug**
Boosts information - Display buff changes not working.
No timer displayed

**To Reproduce**
Enable plugin, enable display buff changes, boost stats.

**Expected behavior**
Display a timer for the next debuff

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Latest
 - Launcher version: Latest

**Additional context**
Not working since several versions ago.

**Comment by farhan1666** [comment]
Was working for me last version but not this version

**Comment by Kyleeld** [comment]
fixed in #923
