### ISSUE TITLE
ShiftToWalk + WorldHopper combination - Shift+Button causes a click whilst hopping

### ISSUE THREAD

**Issue by Icenix** [runelite-extended/runelite#906]
**Describe the bug**
If both the Shift to Walk + World Hopper plugin are enabled, and the World Hopper is set to hop worlds with a combination involving the shift key;
Attempting to switch worlds registers a click on screen.
Causing you to walk/run around if you can't yet logout due to combat timer.

**To Reproduce**
Enable Shift to Walk plugin
Enable World Hopper Plugin
Assign the world hopper plugin a combination involving the shift key (eg, ctrl+shift+left arrow, or shift+x)

**Expected behavior**
Do not register a click from the key combinations

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Latest
 - Launcher version: Latest

**Comment by whocodes** [comment]
I am unable to reproduce this issue.

![](https://i.imgur.com/yoq5tEW.png)

**Comment by Icenix** [comment]
![image](https://user-images.githubusercontent.com/52366085/60766265-ee6d5200-a0d9-11e9-830f-a43706b42fb5.png)

![image](https://user-images.githubusercontent.com/52366085/60766271-fcbb6e00-a0d9-11e9-8d84-d1bf50c0a154.png)

![image](https://user-images.githubusercontent.com/52366085/60766286-1c529680-a0da-11e9-8229-c106005ba9cf.png)
