### ISSUE TITLE
Can't left click to deposit Coal Bag in bank with Menu Entry Swapper "Swap Coal Bag Empty"

### ISSUE THREAD

**Issue by Icenix** [runelite-extended/runelite#907]
**Describe the bug**
If the Menu Entry Swapper plugin is enabled, and the "Swap Coal Bag Empty" option is enabled;
You can not left click on a coal bag whilst in bank to deposit it (left click option is Deposit-1 Coal Bag), you have to right click + Deposit

Holding shift and clicking the coal bag deposits it.
Menu entry does not change.

**To Reproduce**
Enable Menu Entry Swapper + Swap Coal Bag Empty option
Attempt to deposit coal bag via left click in bank

**Expected behavior**
Deposit coal bag whilst in bank interface with left click

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Latest
 - Launcher version: Latest

**Comment by se7enAte9** [comment]
This is a visual bug, but the options are still being swapped. That setting swaps empty with deposit-1 until you press shift which temporarily disables the swap. If the visual bug bothers you, you can add `deposit-1,coal bag:empty,coal bag` to custom swaps until this is fixed (although pressing shift to disable the swap wouldn't function anymore).

**Comment by whocodes** [comment]
`Pay` for Farming helpers quit working when I updated my build today.

#805 (not rly sure which one this should go under, but we hardly need 300 issues with each thing that breaks in menu swapper)

**Comment by xKylee** [comment]
with the latest MES changes, can you confirm if this is still a bug?

**Comment by xKylee** [comment]
tested by @Crystalknockt

this works fine after the MES changes.
