### ISSUE TITLE
Player notifier for non pvp worlds/non-wilderness

### ISSUE THREAD

**Issue by wdbbb** [runelite-extended/runelite#911]
It would be very helpful to have a player notifier, identical to the pker notifier.

Instead, it would be able to work on non pvp worlds, not in the wilderness. 

 For instance when doing mm2 agility, most people stop and ask what you’re doing.
I'd like to know when I am going to have to respond to someone.

**Comment by Kyleeld** [comment]
i mean, if you wasnt botting, this wouldnt be an issue ;)

**Comment by Kyleeld** [comment]
we could make it work for PVP/wilderness, but thats it, non pvp worlds and non wilderness would be a hard no.
