### ISSUE TITLE
Client will not load.

### ISSUE THREAD

**Issue by Aplastars** [runelite-extended/runelite#919]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I double click on the runeliteplus client and it stays at the splash screen saying "starting runelite injector"

**To Reproduce**
literally double clicking on the client .exe and just wait

**Expected behavior**
stays at the splash screen never loads the client.
![runelitenotloading](https://user-images.githubusercontent.com/52623557/60766993-0663b800-a07f-11e9-88d5-a190575bf25d.png)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - RuneLite version: 1.5.29-SNAPSHOT
 - Launcher version: Plus version 2.0.1-1

**Additional context**
https://pastebin.com/qv3KAbKN
https://pastebin.com/4sFh2cuP

**Comment by zeruth** [comment]
willing to bet you its because you aren't using Oracle JDK8

**Comment by f0rmatme** [comment]
try https://www.runelitepl.us/RuneLitePlusSetup.exe
