### ISSUE TITLE
Colorized Player Menu

### ISSUE THREAD

**Issue by imjustgaming** [runelite-extended/runelite#929]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Right-click option to highlight names in a certain color doesn't appear to be working. 

**Expected behavior**
Right-click player names should be highlighted in a color. The colorized player menu option is also checked.

**Screenshots**
![image](https://user-images.githubusercontent.com/52637592/60774243-b9521580-a154-11e9-8c86-cb26dba5b137.png)

How it should look like (Vanilla Runelite client) 
![image](https://user-images.githubusercontent.com/52637592/60774252-d4bd2080-a154-11e9-990e-0f6df9be1eea.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.29
 - Launcher version: 1.5.2

**Additional context**
However, all other features (tiles,names above heads and minimap) all work:

![image](https://user-images.githubusercontent.com/52637592/60774398-ca9c2180-a156-11e9-9be0-fcd45d47d402.png)

It also isn't just non-clan member specific. Adding someone to the target,caller,friends list also doesn't work.

![image](https://user-images.githubusercontent.com/52637592/60774403-e99ab380-a156-11e9-9b1f-bd690fd3f5ee.png)

**Comment by se7enAte9** [comment]
In work, see #899
