### ISSUE TITLE
Rune Pouch Font

### ISSUE THREAD

**Issue by laska89** [runelite-extended/runelite#933]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Changing runelite font does not change the font overlayed on the rune pouch. It remains the same bold font no matter what.

**To Reproduce**
1. Go to settings > runelite > font
2. Change font
3. No change. Still bold font (https://i.imgur.com/olbdLYf.png)

**Expected behavior**
Font should change.

**Screenshots**
https://i.imgur.com/olbdLYf.png

**Environment (please complete the following information):**
1.5.29 with the July 8 bugfixes

**Additional context**

**Comment by Abi1024** [comment]
It should be noted that the RunePouch plugin is from the base RuneLite plugins and is not one of the RL+ plugins.
