### ISSUE TITLE
Client crash in inferno

### ISSUE THREAD

**Issue by Vegetah** [runelite-extended/runelite#938]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
A clear and concise description of what 
[hs_err_pid10672.log](https://github.com/runelite-extended/runelite/files/3368480/hs_err_pid10672.log)
the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Kyleeld** [comment]
That’s an actual java crash, not rl+

**Comment by Vegetah** [comment]
Anny idea how i can fix it?

Op ma 8 jul. 2019 15:37 schreef Kyleeld <notifications@github.com>:
