### ISSUE TITLE
Lizard Shaman spawn timer not working

### ISSUE THREAD

**Issue by creglol** [runelite-extended/runelite#954]
Describe the bug
The Lizard Shamans plug-in does not seem to function when attacking the Shamans in the Lizardmen Temple in Molch (Kebos Lowlands). (Was working 2 days or so ago but has randomly stopped, I've not checked other areas).

To Reproduce

Go to the Lizardmen Temple in Molch
Enable the Lizard Shamans Plugin
Attack Lizardman shamans
Notice that the plugin does not function in this case.
Expected behavior
For the plugin to function (show timer on Lizardman spawns) when attacking Lizardman Shamans in the Molch Temple.

RuneLite version: 1.5.29-SNAPSHOT
Launcher version: 1.6.3-SNAPSHOT

**Comment by Kyleeld** [comment]
Can you confirm if this works for them outside of the temple?

**Comment by creglol** [comment]
Yes, can confirm - just tested.

**Comment by creglol** [comment]
Can confirm that it is not working for the canyon Shamans either

**Comment by Owain94** [comment]
@Kyleeld you were wrong about the message type on Discord the other day 😜

Remove message type check from the if guard inside the plugin to fix this

I’ll send a PR tomorrow if you don’t beat me to it

**Comment by Owain94** [comment]
Fixed in #968
