### ISSUE TITLE
Ice cooler showing up on baby black dragons

### ISSUE THREAD

**Issue by Ripsinthepaper** [runelite-extended/runelite#964]
Killing baby black dragons, and when it's close to dying, it shows the ice cooler icon.
![Gjc9mmi](https://user-images.githubusercontent.com/39879075/60950904-526d6180-a2f8-11e9-8bb4-aeb095e35145.png)

**Comment by JourneyOver** [comment]
Might as well add to this, it shows up on baby green dragons as well.

Possibly shows up on all baby dragons more than likely xD

**Comment by SRLJustin** [comment]
Can you please log and post the animations used by the babydragons? Animations can be found in the dev tools

**Comment by JourneyOver** [comment]
Well I went to go get baby green dragons animations, and it seems that this issue at least doesn't exist on them anymore from what I can see as the ice cooler no longer is showing up on them.

But either way just in case here are the animations regardless.

animations for baby green dragons - 
Attacking player: 25
Defending from player: 26
death: 28

**Comment by Ripsinthepaper** [comment]
Attacking 25
Defending 26
Death 28

Still shows up for me on baby black dragons

**Comment by SRLJustin** [comment]
@Ganom https://i.imgur.com/ghYZBLK.gifv

Not sure where the other issue went where you requested this info

**Comment by Kyleeld** [comment]
#429
