### ISSUE TITLE
Shift Toggle

### ISSUE THREAD

**Issue by whocodes** [runelite-extended/runelite#977]
**Describe the feature you'd like**
An option to set a keybind to toggle whether or not the game thinks you're holding down shift.

**Additional context**
This would be very useful for things such as power-mining or power-fishing, where you'd be consistently pressing shift and clicking to drop items. This would allow you to click only once, without the need to even touch your keyboard.

I am aware that this can be achieved with menu swaps, however this solution would also work for other things that are toggled by using the shift key, and will also work without having to modify your menu swaps for each new item.

**Comment by Kyleeld** [comment]
this isnt something we will implement.
