### ISSUE TITLE
Cant vengeance friends/clan members

### ISSUE THREAD

**Issue by Crystalknoct** [runelite-extended/runelite#993]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I try to cast vengeance other on a clan mate or a friend and it acts like its not even an option thats possible.
**To Reproduce**
1. Go to 'Runelite+ spell book'
2. Click on 'Vengeance other'
3. Scroll down to 'Any friend or clan mate'
No error produced.
**Expected behavior**
I expected to be able to just cast vengeance on my clan members and friends for raids/ and other things that include pvm. I dont use and pvp plugins so that shouldn't be an issue of conflicting preventing me from using vengeance.
**Screenshots**
https://i.imgur.com/fegrzVX.png
**Environment (please complete the following information):**
 - OS: [Windows 10]
 - RuneLite version: [1.5.29-SNAPSHOT]
 - Launcher version: [Unknown]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

[application.log](https://github.com/runelite-extended/runelite/files/3387803/application.log)
[client.log](https://github.com/runelite-extended/runelite/files/3387805/client.log)
[launcher.log](https://github.com/runelite-extended/runelite/files/3387806/launcher.log)

**Comment by Kyleeld** [comment]
Please use the search feature I. Discord first it’s been raised a million times
